.github/workflows/build.yml
Dockerfile

ci: fix build workflow

---

server/pkg/builtin/manifest.yml
server/pkg/builtin/manifest_ja.yml

feat(server): add field to manifest to allow for entering the ground

---

server/pkg/builtin/manifest.yml
server/pkg/builtin/manifest_ja.yml

To fix this issue: https://github.com/reearth/reearth/issues/319

fix(server): Tiles typo error

---

server/pkg/builtin/manifest.yml
server/pkg/builtin/manifest_ja.yml

feat: add htmlblock to built-in plugin

---

server/pkg/builtin/manifest.yml
server/pkg/builtin/manifest_ja.yml

fix(server): htmlblock order

---

web/src/core/Crust/index.tsx

This is a test PR for checking the workflow for reearth/web test deployment.

ci: made redundant change in web

---

web/src/core/Crust/index.tsx

This PR reverts redundant change made on web for workflow testing purpose.

ci: revert redundant changes on web

---

.github/workflows/ci_collect_info.yml

This PR fixes a small bug caused by https://github.com/reearth/reearth/pull/414

ci: fix add release in ci-collect-info

---

web/package.json
web/src/auth/hooks.ts
web/src/auth/provider.tsx
web/yarn.lock

chore(web): upgrade auth0 to version 2

---

web/package.json
web/yarn.lock

This PR updates to cesium `v1.105.2` from `v1.105.1` as has the following issue causing issue in our system.
ref: https://github.com/CesiumGS/cesium/issues/11278

fix(web): update cesium version to 1.105.2 from 1.105.1

---

.github/workflows/ci_web_build.yml

This PR fixes the order of execution of the build-web workflow.

ci: fix order of build-web workflow execution

---

web/src/classic/core/Crust/Plugins/PluginFrame/IFrame/index.stories.tsx
web/src/classic/core/Crust/Plugins/PluginFrame/SafeIFrame/index.stories.tsx
web/src/classic/core/Crust/Plugins/PluginFrame/index.stories.tsx

fix(web): stories name conflicts

---

web/src/classic/core/Visualizer/Error.tsx
web/src/classic/core/Visualizer/index.tsx

Fixed to handle error as same with previous Visualizer.

fix(web): use error boundary in core Visualizer

---

web/src/beta/components/TabButton/index.stories.tsx
web/src/beta/components/TabButton/index.test.tsx
web/src/beta/components/TabButton/index.tsx

chore(web): Add TabButton component

---

.github/workflows/release.yml

This PR adds functionality for automatic version update of reearth/web when release action has been executed.

ci: auto update reearth/web version with release

---

.github/workflows/ci.yml
.github/workflows/ci_server.yml
.github/workflows/ci_server_build.yml
.github/workflows/ci_web.yml
.github/workflows/ci_web_build.yml

This PR adds a refactor the ci workflow for checking and testing of the changed files.

ci: use reusable workflows for ci workflow

---

.github/workflows/release.yml

ci: Revert auto update reearth/web version with release

---

.github/workflows/build_server.yml
.github/workflows/build_web.yml
.github/workflows/ci.yml

ci: fix skipped build workflow when pushed on main

---

.github/workflows/build_server.yml
.github/workflows/build_web.yml
.github/workflows/ci.yml
.github/workflows/ci_collect_info.yml

Dummy PR for dummy test of actions.

ci(server, web): fix workflow dispatch input for correct ref head_branch

---

web/src/classic/components/organisms/Published/core/hooks.ts
web/src/classic/components/organisms/Published/core/index.tsx

fix(web): revert published page VR layer selection

---

web/src/beta/lib/core/Crust/Plugins/plugin_types.ts

fix(web): typing for window in beta

---

.github/workflows/build_server.yml
.github/workflows/build_web.yml

This PR fixes the docker release bug observed recently which was caused by a typo.

ci: fix release pipeline bug

---

server/internal/infrastructure/mongo/property.go

fix(server): filter properties in property.FindByIDs

---

web/src/beta/lib/core/engines/Cesium/core/presets.ts
web/src/classic/components/molecules/Visualizer/Engine/Cesium/core/presets.ts
web/src/classic/core/engines/Cesium/core/presets.ts

fix: force jpg for watercolor tile

---

web/package.json

update to new big version v0.17.0

chore(web): update package.json to v0.17.0

---

web/src/beta/lib/core/engines/Cesium/PostProcesses/hbao/AmbientOcclusion.tsx

fix(web): camera frustum for ambient occlusion

---

server/internal/infrastructure/mongo/dataset.go

perf(server): improve dataset index

---

server/internal/infrastructure/mongo/layer.go

perf(server): add group.linkeddatasetschema index

---

web/src/beta/lib/core/engines/Cesium/Feature/index.tsx
web/src/classic/core/engines/Cesium/Feature/index.tsx

`data.url` could be a large text when using as dataUrl. Generating MD5 of this in each update is very heavy and lead to performance issue.
| Before      | After |
| ----------- | ----------- |
|    ![image](https://github.com/reearth/reearth/assets/21994748/9ac7a100-bb54-4ee7-ad89-623a7b414c89)|     ![image (1)](https://github.com/reearth/reearth/assets/21994748/bac19a79-9b4b-486c-99dd-7a425bf63755)|
- Memo MD5 of data.url and connect it with MD5 generated with other props as feature component ID.
- Both classic and beta.
```js
reearth.layers.add({
data: {
type: "csv",
url: "data:text/plain;charset=UTF-8,%E7%AE%A1%E8%BD%84%E7%BD%B2%E6%89%80%2C%E5%8C%97%E7%B7%AF%2C%E6%9D%B1%E7%B5%8C%0D%0A%E8%A5%BF%E5%8C%BA%2C35.87070833%2C139.5714333%0D%0A%E8%A5%BF%E5%8C%BA%2C35.87081389%2C1 …
```

fix(web): performance issue when generate md5 with large data.url

---

web/src/beta/lib/core/Crust/Infobox/Block/builtin/unsafeBlocks.ts
web/src/beta/lib/core/Crust/Widgets/Widget/builtin/unsafeWidgets.ts
web/src/services/config/extensions.ts

fix(web): pr preview build failing

---

web/src/beta/lib/core/Crust/Infobox/Block/builtin/unsafeBlocks.ts
web/src/beta/lib/core/Crust/Widgets/Widget/builtin/unsafeWidgets.ts
web/src/beta/lib/core/Crust/types.ts
web/src/services/config/index.ts
web/src/services/config/unsafeBuiltinPlugin.ts

fix(web): unsafe builtin implementation

---

web/src/beta/components/ListItem/index.tsx
web/src/beta/components/PopoverMenuContent/index.tsx
web/src/beta/features/Editor/tabs/story/PageIndicator/index.tsx
web/src/beta/features/Editor/tabs/story/SidePanel/Action/index.tsx
web/src/beta/features/Editor/tabs/story/SidePanel/PageItemWrapper/index.tsx
web/src/beta/features/Modals/WorkspaceCreationModal/index.tsx

chore(web): update hexadecimal colors

---

server/e2e/gql_nlslayer_test.go
server/gql/newlayer.graphql
server/internal/adapter/gql/generated.go
server/internal/adapter/gql/gqlmodel/models_gen.go
server/internal/adapter/gql/resolver_mutation_nlslayer.go
server/internal/usecase/interactor/nlslayer.go
server/internal/usecase/interfaces/nlslayer.go
server/pkg/nlslayer/nlslayerops/intializer.go

This PR makes small refactor to mutation made for adding a simple NLS layer.

chore(sever): refactor around NLS layers

---

web/src/beta/lib/lexical/RichTextEditor/index.css

Correct the css class selector.

chore(web): correct style of story text block

---

web/src/beta/lib/core/engines/Cesium/hooks.ts

chore(web): override default light

---

web/src/beta/features/Editor/StoryPanel/Page/index.tsx
web/src/beta/features/Editor/StoryPanel/PanelContent/index.tsx
web/src/beta/features/Editor/StoryPanel/hooks.ts
web/src/beta/features/Editor/StoryPanel/index.tsx
web/src/beta/features/Editor/Visualizer/CanvasArea/hooks.ts
web/src/beta/features/Editor/index.tsx
web/src/beta/features/Editor/useLeftPanel.tsx
web/src/beta/features/Editor/useRightPanel.tsx
web/src/beta/features/Editor/useStorytelling.ts

chore(web): story page change on user scroll

---

web/src/beta/features/Editor/Visualizer/CanvasArea/hooks.ts

chore(web): fix inifinite loop while selecting layer

---

web/src/beta/lib/core/Crust/Plugins/api.ts
web/src/beta/lib/core/Crust/Plugins/hooks.ts
web/src/beta/lib/core/Crust/Plugins/plugin_types.ts
web/src/beta/lib/core/Crust/Plugins/storybook.tsx
web/src/beta/lib/core/Map/ref.ts
web/src/beta/lib/core/Map/types/index.ts
web/src/beta/lib/core/engines/Cesium/common.ts
web/src/beta/lib/core/engines/Cesium/useEngineRef.ts

Add a new plugin API `reearth.camera.getFovCenter`
```ts
reearth.camera.getFovCenter(withTerrain?:boolean) => LatLngHeight | undefined
```
- without terrian
```js
reearth.scene.overrideProperty({
terrain:{
terrain: false,
// for better obvious the point
depthTestAgainstTerrain: true,
}
})
const update = () => {
// Override data value will not update since the feature is been cached. 
// Therefore in this test i remove and add new layers on update.
reearth.layers.layers
.map(l => l.id)
.forEach(id => {
reearth.layers.delete(id);
});
const position = reearth.camera.getFovCenter();
console.log(position);
if (!position) return;
reearth.layers.add({
data: {
type: "geojson",
value: {
type: "Feature",
geometry: {
coordinates: [position.lng, position.lat, position.height],
type: …
```

chore(web): add pluginAPI camera.getFovCenter

---

web/src/beta/components/fields/NumberField/index.stories.tsx
web/src/beta/components/fields/NumberField/index.tsx
web/src/beta/components/fields/PropertyFields/index.tsx
web/src/beta/components/fields/common/NumberInput/index.tsx

chore(web): add number field

---

web/src/beta/components/fields/CameraField/index.tsx

Making camera field responsive
Just CSS changes on the input field
[Screencast from 12-09-23 11:39:58 AM IST.webm](https://github.com/reearth/reearth/assets/20891087/72797740-e92b-45cf-97d3-d68025b9b9a3)
- NA
- Responsive element in the TabMenu
NA
NA

chore(web): Camera field responsiveness

---

server/e2e/gql_storytelling_test.go
server/pkg/scene/builder/story.go

This PR adds pluginId and extensionId fields in the block JSON created while publishing story.

chore(server): add extensionId and pluginId in block json of published story

---

web/src/beta/features/Editor/Visualizer/hooks.ts
web/src/beta/features/Editor/Visualizer/index.tsx
web/src/beta/features/Editor/index.tsx
web/src/beta/features/Editor/tabs/story/LeftPanel/ContentPage/index.stories.tsx
web/src/beta/features/Editor/tabs/story/LeftPanel/ContentPage/index.tsx
web/src/beta/features/Editor/tabs/story/LeftPanel/index.tsx
web/src/beta/features/Editor/tabs/story/RightPanel/index.tsx
web/src/beta/features/Editor/useLeftPanel.tsx
web/src/beta/features/Editor/useRightPanel.tsx
web/src/beta/features/Editor/useStorytelling.ts
web/src/beta/lib/core/StoryPanel/ActionPanel/index.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/common/ActionPanel/index.tsx
web/src/beta/lib/core/StoryPanel/Page/BlockAddBar.tsx
web/src/beta/lib/core/StoryPanel/Page/hooks.ts
web/src/beta/lib/core/StoryPanel/Page/index.tsx
web/src/beta/lib/core/StoryPanel/PanelContent/index.tsx
web/src/beta/lib/core/StoryPanel/hooks.ts
web/src/beta/lib/core/StoryPanel/index.tsx
web/src/beta/lib/core/mantle/types/value.ts
web/src/beta/pages/Page.tsx
web/src/services/api/index.ts
web/src/services/api/propertyApi/utils.ts
web/src/services/api/storytellingApi/index.ts
web/src/services/api/storytellingApi/utils.ts

StoryPanel refactor
WIP: add camera fly to to story page change. The refactor is needed for another dev so this will be finalized in another PR

chore(web): refactor storypanel to remove any gql use

---

web/src/beta/features/Editor/Visualizer/hooks.ts
web/src/beta/features/Editor/Visualizer/index.tsx
web/src/beta/features/Editor/hooks.ts
web/src/beta/features/Editor/index.tsx
web/src/beta/features/Editor/tabs/story/LeftPanel/ContentPage/index.stories.tsx
web/src/beta/features/Editor/tabs/story/LeftPanel/ContentPage/index.tsx
web/src/beta/features/Editor/tabs/story/LeftPanel/index.tsx
web/src/beta/features/Editor/useLeftPanel.tsx
web/src/beta/features/Editor/useStorytelling.ts
web/src/beta/lib/core/StoryPanel/Page/index.tsx
web/src/beta/lib/core/StoryPanel/PanelContent/index.tsx
web/src/beta/lib/core/StoryPanel/hooks.ts
web/src/beta/lib/core/StoryPanel/index.tsx
web/src/services/api/storytellingApi/index.ts

chore(web): Story page camera transition

---

web/src/beta/lib/core/StoryPanel/Page/BlockAddBar.tsx
web/src/beta/lib/core/StoryPanel/PanelContent/index.tsx

chore(web): fix story page/block ui/ux

---

web/src/beta/lib/core/mantle/atoms/compute.ts

chore(web): fix a layer update process

---

web/src/beta/lib/lexical/RichTextEditor/plugins/ToolbarPlugin.tsx

This PR updates font size options of story text block and fixed a bug of lexical with solution from lexical issue page.

chore(web): update story text block fontsize options

---

web/src/beta/components/Modal/index.tsx

- fix page re-render after upload csv file in add from local

chore(web): fix upload file bug

---

web/src/beta/components/fields/common/NumberInput/index.tsx

fix(web): trim leading zeros from number fields

---

web/src/beta/features/Editor/Visualizer/index.tsx
web/src/beta/features/Editor/index.tsx
web/src/beta/features/Editor/useStorytelling.ts
web/src/beta/lib/core/StoryPanel/PanelContent/hooks.ts
web/src/beta/lib/core/StoryPanel/PanelContent/index.tsx
web/src/beta/lib/core/StoryPanel/index.tsx

chore(web): camera issues in storytelling

---

server/internal/usecase/interactor/project.go

When the policy was changed, it was still possible to update existing projects (publish more projects that were already published) without limitation. In this PR, the limit on the number of published projects was changed so that it also applies to project updates.

fix(server): check project count to ensure policy on project republication

---

web/src/beta/lib/core/engines/Cesium/Feature/index.tsx

chore(web): fix visible state

---

web/src/beta/features/Editor/tabs/map/BottomPanel/LayerStyleCard.tsx
web/src/beta/features/Editor/useLayerStyles.ts
web/src/beta/features/Modals/LayerStyleModal/hooks.ts
web/src/beta/features/Modals/LayerStyleModal/index.tsx

chore(web): fixes and refactoring to layer style system

---

server/e2e/gql_storytelling_test.go
server/internal/usecase/interactor/project.go
server/internal/usecase/interactor/storytelling.go
server/pkg/scene/builder/builder.go
server/pkg/scene/builder/layerStyle.go
server/pkg/scene/builder/scene.go

This PR adds `layerStyles` as one of the fields in the a published project and story JSONs.

chore(server): add layerStyles to publishing

---

server/gql/storytelling.graphql
server/internal/adapter/gql/generated.go
server/internal/adapter/gql/gqlmodel/models_gen.go
server/internal/usecase/interactor/storytelling.go
server/internal/usecase/interfaces/story.go
server/pkg/storytelling/story.go

This PR adds `bgColor` in story and the revelant changes has been made to update them through the update mutation on the story.

chore(server): add bgColor to story

---

web/src/beta/features/Editor/Visualizer/hooks.ts
web/src/beta/features/Editor/tabs/map/RightPanel/LayerInspector/FeatureData.tsx
web/src/beta/features/Editor/tabs/map/RightPanel/LayerInspector/LayerData.tsx
web/src/beta/features/Editor/tabs/map/RightPanel/LayerInspector/index.tsx
web/src/beta/lib/core/Visualizer/hooks.ts
web/src/beta/lib/core/Visualizer/index.tsx
web/src/beta/lib/core/engines/Cesium/index.tsx
web/src/services/state/index.ts

chore(web): 3dtile feature select support in UI

---

web/src/beta/features/Editor/Visualizer/convert-story.ts
web/src/beta/features/Editor/Visualizer/hooks.ts
web/src/beta/features/Editor/Visualizer/index.tsx
web/src/beta/features/Modals/AssetModal/index.tsx
web/src/beta/lib/core/StoryPanel/ActionPanel/index.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/Camera/Content.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/Camera/Editor/hooks.ts
web/src/beta/lib/core/StoryPanel/Block/builtin/Camera/Editor/index.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/Camera/index.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/Markdown/index.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/Text/Editor.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/Text/index.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/common/ActionPanel/index.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/common/Wrapper.tsx
web/src/beta/lib/core/StoryPanel/Block/types.ts
web/src/beta/lib/core/StoryPanel/Page/index.tsx
web/src/beta/lib/core/StoryPanel/PanelContent/index.tsx
web/src/beta/lib/core/StoryPanel/SelectableArea/index.tsx
web/src/beta/lib/core/StoryPanel/hooks/useFieldComponent.tsx
web/src/beta/lib/core/StoryPanel/index.tsx
web/src/services/api/propertyApi/index.ts

chore(web): bug fixes

---

web/src/beta/components/Resizable/index.tsx
web/src/beta/features/Editor/BottomPanel/index.tsx
web/src/beta/features/Editor/SecondaryNav/index.tsx
web/src/beta/features/Editor/SidePanel/index.tsx
web/src/beta/features/Editor/tabs/map/BottomPanel/LayerStyle.tsx
web/src/beta/features/Navbar/LeftSection/index.tsx
web/src/beta/features/Navbar/index.tsx
web/src/beta/features/Notification/hooks.ts
web/src/beta/features/Notification/index.tsx

chore(web): UI updates

---

web/src/beta/components/CatalogCard/index.tsx
web/src/beta/components/fields/TextField/index.tsx
web/src/beta/components/fields/common/TextInput/index.tsx
web/src/beta/features/Editor/tabs/map/BottomPanel/LayerStyleCard.tsx
web/src/beta/features/Editor/tabs/map/LeftPanel/Layers/LayerItem.tsx
web/src/beta/features/ProjectSettings/innerPages/GeneralSettings/index.tsx
web/src/beta/features/ProjectSettings/innerPages/PluginSettings/PluginInstall/PublicRepo/index.tsx
web/src/beta/features/ProjectSettings/innerPages/PublicSettings/PublicSettingsDetail.tsx

This pr is to remove the time out from text input

chore: remove the timeOut from text input

---

web/src/beta/lib/core/Map/Layers/hooks.ts
web/src/beta/lib/core/mantle/evaluator/simple/index.ts

chore(web): fix overriding layer structure

---

web/src/beta/features/Editor/hooks.ts
web/src/beta/features/Editor/index.tsx
web/src/beta/features/Editor/tabs/story/LeftPanel/ContentPage/PageItem.tsx
web/src/beta/features/Editor/tabs/story/LeftPanel/ContentPage/index.tsx
web/src/beta/features/Editor/tabs/story/LeftPanel/index.tsx
web/src/beta/features/Editor/useLeftPanel.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/Timeline/Editor.tsx

- double click to edit page name

chore(web): double click on page name

---

web/src/beta/components/fields/DateTimeField/index.tsx
web/src/beta/components/fields/TimelineField/EditPanel/index.tsx

chore(web): fix timeline field component's popover

---

web/src/beta/components/fields/DateTimeField/EditPanel/index.tsx
web/src/beta/components/fields/SelectField/index.tsx

the pop over when chosen the time zone looks weird, this pr is  to fix that

chore: fix input field popover

---

web/src/beta/lib/core/StoryPanel/ActionPanel/index.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/common/ActionPanel/index.tsx
web/src/beta/lib/core/StoryPanel/Page/index.tsx
web/src/beta/lib/core/StoryPanel/SelectableArea/index.tsx

The setting weren't applied successfully , this pr to fix that

chore(web): fix padding settings for page

---

server/pkg/builtin/manifest.yml

Adding the padding setting to the title story page in manifest

chore(server): add panel setting to manifest

---

server/pkg/builtin/manifest.yml

chore: modify the description of zoom level

---

server/pkg/builtin/manifest.yml
server/pkg/builtin/manifest_ja.yml
web/src/beta/features/Editor/DataSourceManager/index.tsx
web/src/services/i18n/translations/en.yml
web/src/services/i18n/translations/ja.yml

chore(web): finalize Japanese translations

---

web/src/beta/features/Editor/index.tsx
web/src/beta/features/Navbar/index.tsx
web/src/beta/features/Navbar/useRightSection.tsx
web/src/beta/features/ProjectSettings/innerPages/PublicSettings/index.tsx
web/src/beta/features/PublishedVisualizer/hooks.ts
web/src/beta/hooks/navigationHooks.ts
web/src/beta/lib/core/StoryPanel/hooks.ts

- tab change causing camera to move to the current page's camera position
- can't select project public settings in new settings page
- etc

chore(web): fixing a few bugs

---

web/src/beta/components/RadioGroup/RadioBox/index.stories.tsx
web/src/beta/components/RadioGroup/RadioBox/index.tsx
web/src/beta/components/RadioGroup/index.tsx
web/src/beta/features/Assets/hooks.ts
web/src/beta/features/Editor/Visualizer/convert-story.ts
web/src/beta/lib/core/StoryPanel/hooks/useFieldComponent.tsx
web/src/beta/lib/core/StoryPanel/index.tsx
web/src/services/api/projectApi.ts

chore(web): fix assets not refetching

---

web/src/beta/components/CheckboxField/index.tsx
web/src/beta/components/ListItem/index.tsx
web/src/beta/components/fields/CameraField/index.tsx
web/src/beta/features/Editor/tabs/map/LeftPanel/Layers/LayerItem.tsx
web/src/services/api/pluginsApi.ts

- Layer name overflowing, pushing icons over (map tab, left panel)
- List of layers in story teb, right panel, overflow issue
- Freshly installed plugins not showing in installable widget list until refresh
- When making side panel width smaller, camera field ui broke

chore(web): multiple bug fixes

---

web/src/app.tsx
web/src/beta/features/GlobalModal/index.tsx
web/src/beta/pages/Page.tsx

fix(web): GlobalModal not showing when it should

---

web/src/beta/lib/core/StoryPanel/ActionPanel/index.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/common/ActionPanel/hooks.ts
web/src/beta/lib/core/StoryPanel/Block/builtin/common/ActionPanel/index.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/common/Wrapper.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/common/hooks.ts
web/src/beta/lib/core/StoryPanel/Page/BlockAddBar.tsx
web/src/beta/lib/core/StoryPanel/Page/hooks.ts
web/src/beta/lib/core/StoryPanel/Page/index.tsx
web/src/beta/lib/core/StoryPanel/PanelContent/hooks.ts
web/src/beta/lib/core/StoryPanel/PanelContent/index.tsx
web/src/beta/lib/core/StoryPanel/SelectableArea/hooks.ts
web/src/beta/lib/core/StoryPanel/SelectableArea/index.tsx
web/src/beta/lib/core/StoryPanel/context.tsx
web/src/beta/lib/core/StoryPanel/hooks.ts
web/src/beta/lib/core/StoryPanel/index.tsx
web/src/beta/lib/core/StoryPanel/utils.ts
web/src/services/theme/reearthTheme/common/zIndex.ts

chore(web): improve Story Panel UX

---

web/src/beta/lib/core/Crust/Plugins/api.ts
web/src/beta/lib/core/Crust/Plugins/hooks.ts
web/src/beta/lib/core/Crust/Plugins/plugin_types.ts
web/src/beta/lib/core/Crust/Plugins/storybook.tsx
web/src/beta/lib/core/Map/ref.ts
web/src/beta/lib/core/Map/types/index.ts
web/src/beta/lib/core/engines/Cesium/useEngineRef.ts

This is a function to fly to the bounding box(bbox) to fit with it.

chore(web): add flyToBBox

---

web/src/beta/lib/core/Map/types/index.ts
web/src/beta/lib/core/engines/Cesium/Feature/Tileset/index.tsx
web/src/beta/lib/core/engines/Cesium/hooks.ts
web/src/beta/lib/core/mantle/types/appearance.ts

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=e3d2c9bd6e1c40e992d277ed52a70baf&pm=s
add types on SceneProperty and Cesium3DTilesetAppearance
add debug codes on web/src/beta/lib/core/engines/Cesium/hooks.ts and web/src/beta/lib/core/engines/Cesium/Feature/Tileset/index.tsx
debug

chore: Wireframe for globe and tileset

---

web/src/beta/lib/core/engines/Cesium/Feature/Marker/index.tsx
web/src/beta/lib/core/engines/Cesium/Feature/Polygon/index.tsx
web/src/beta/lib/core/engines/Cesium/Feature/Polyline/index.tsx
web/src/beta/lib/core/engines/Cesium/Feature/utils.tsx
web/src/beta/lib/core/engines/Cesium/hooks.ts
web/src/beta/lib/core/mantle/types/appearance.ts

Add hideIndicator On Selecting
add: hideindicator on polygon, marker, polyline type

chore(web): Add hideIndicator On Selecting

---

web/src/beta/utils/time.ts

Invalid date is also instance of Date, we need to check it and ignore it if it's invalid.

chore(web): handle invalid date in time convert

---

web/src/beta/components/fields/ColorField/hooks.ts
web/src/beta/components/fields/ColorField/types.ts
web/src/beta/components/fields/URLField/index.tsx
web/src/beta/lib/core/Crust/Widgets/Widget/builtin/Button/MenuButton.tsx
web/src/beta/lib/core/StoryPanel/Block/builtin/Camera/Editor/hooks.ts
web/yarn.lock

Additionally fixed the button widget not showing the icon

chore(web): allow undefined input for color and url fields

---

web/src/beta/lib/core/engines/Cesium/VertexTerrainElevationMaterial.ts
web/src/beta/lib/core/engines/Cesium/core/Imagery.tsx
web/src/beta/lib/core/engines/Cesium/core/presets.ts

fix(web): use cesium's material

---

web/src/beta/lib/core/engines/Cesium/Feature/Marker/index.tsx
web/src/beta/lib/core/engines/Cesium/Feature/Raster/hooks.ts
web/src/beta/lib/core/engines/Cesium/hooks.ts
web/src/beta/lib/core/mantle/types/appearance.ts

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=5a8dbc7df50f4aaf8b4bb7575e2b2f00&pm=s

chore(web): Hide indicator for imagery layer

---

web/src/beta/lib/core/engines/Cesium/Feature/Box/Edge.tsx
web/src/beta/lib/core/engines/Cesium/Feature/Box/ScalePoints.tsx
web/src/beta/lib/core/engines/Cesium/Feature/Box/Side.tsx
web/src/beta/lib/core/engines/Cesium/Feature/Box/index.tsx
web/src/beta/lib/core/mantle/types/appearance.ts

chore(web): hide indicator for box

---

web/src/beta/lib/core/Crust/Plugins/hooks.ts

chore(web): fix the issue that multiple selection isn't working well

---

web/src/beta/components/fields/CameraField/CapturePanel/index.tsx
web/src/beta/components/fields/CameraField/EditPanel/hooks.ts
web/src/beta/components/fields/CameraField/EditPanel/index.tsx
web/src/beta/components/fields/CameraField/index.tsx
web/src/beta/components/fields/CameraField/types.ts
web/src/beta/components/fields/CameraField/utils.ts
web/src/beta/components/fields/common/NumberInput/index.tsx
web/src/beta/features/Editor/SidePanel/Settings/index.tsx
web/src/beta/features/Editor/tabs/widgets/RightPanel/index.tsx
web/src/beta/features/Editor/useRightPanel.tsx
web/src/beta/lib/core/engines/Cesium/Feature/Ellipse/index.tsx

chore(web): fix camera field issues

---

web/src/beta/lib/core/engines/Cesium/Feature/Resource/index.tsx
web/src/beta/lib/core/mantle/types/appearance.ts

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=1b658da20c0c4c7394fbdeb572c99c8a&pm=s

chore(web): Hide indicator for resource

---

server/e2e/gql_nlslayer_test.go
server/e2e/gql_style_test.go
server/gql/newlayer.graphql
server/gql/style.graphql
server/internal/adapter/gql/generated.go
server/internal/adapter/gql/gqlmodel/models_gen.go
server/internal/adapter/gql/resolver_mutation_nlslayer.go
server/internal/adapter/gql/resolver_mutation_style.go
server/internal/usecase/interactor/nlslayer.go
server/internal/usecase/interactor/style.go
server/internal/usecase/interfaces/nlslayer.go
server/internal/usecase/interfaces/style.go
server/pkg/nlslayer/nlslayer.go
server/pkg/scene/style.go
server/pkg/scene/style_test.go

NLSLayer and Layer Style requires to support Duplication, I added appropriate queries and changes to their respective pkg.

feat(server): support style and layer duplication

---

server/gql/project.graphql
server/internal/adapter/gql/generated.go
server/internal/adapter/gql/gqlmodel/convert_project.go
server/internal/adapter/gql/gqlmodel/convert_project_test.go
server/internal/adapter/gql/gqlmodel/models_gen.go
server/internal/adapter/gql/resolver_mutation_project.go
server/internal/infrastructure/mongo/mongodoc/project.go
server/internal/usecase/interactor/project.go
server/internal/usecase/interfaces/project.go
server/pkg/builtin/manifest.yml
server/pkg/builtin/manifest_ja.yml
server/pkg/project/builder.go
server/pkg/project/project.go

This PR adds support for GA with projects.

chore(server): support GA with projects

---

web/package.json
web/src/beta/lib/core/engines/Cesium/Feature/Raster/mvt.ts
web/yarn.lock

Revert "chore(web): mvt provider refactor"

---

web/src/beta/lib/core/Crust/Plugins/hooks.ts
web/src/beta/lib/core/Crust/Plugins/plugin_types.ts
web/src/beta/lib/core/Crust/Plugins/types.ts
web/src/beta/lib/core/Crust/index.tsx
web/src/beta/lib/core/Map/types/index.ts
web/src/beta/lib/core/Visualizer/hooks.ts
web/src/beta/lib/core/Visualizer/index.tsx
web/src/beta/lib/core/engines/Cesium/hooks.ts
web/src/beta/lib/core/engines/Cesium/hooks/useLayerSelectWithDrag.ts
web/src/beta/lib/core/engines/Cesium/hooks/useLayerSelectWithRect.ts
web/src/beta/lib/core/engines/Cesium/index.tsx
web/src/beta/lib/core/engines/Cesium/utils/mouse.ts

I added these three type of events to support selecting multiple feature within the rect.
- LayerSelectWithRectStart
- LayerSelectWithRectMove
- LayerSelectWithRectEnd

chore(web): add layer select with drag event

---

server/e2e/gql_nlslayer_test.go
server/gql/featureCollection.graphql
server/gql/newlayer.graphql
server/internal/adapter/gql/generated.go
server/internal/adapter/gql/gqlmodel/models_gen.go
server/internal/adapter/gql/resolver_mutation_nlslayer.go
server/internal/usecase/interactor/nlslayer.go
server/internal/usecase/interfaces/nlslayer.go
web/src/classic/gql/graphql-client-api.tsx
web/src/classic/gql/graphql.schema.json
web/src/services/gql/__gen__/graphql.ts

This is the PR that adds `schema` as a parameter to `AddNLSLayerSimpleInput`.

chore(server): add schema to nlslayer simple input

---

server/gql/plugin.graphql
server/internal/adapter/gql/generated.go
server/internal/adapter/gql/gqlmodel/convert_plugin.go
server/internal/adapter/gql/gqlmodel/models_gen.go
server/internal/usecase/interactor/nlslayer.go
server/pkg/builtin/main.go
server/pkg/builtin/manifest.yml
server/pkg/plugin/extension.go
server/pkg/plugin/manifest/convert.go
web/src/classic/gql/graphql-client-api.tsx
web/src/classic/gql/graphql.schema.json
web/src/services/gql/__gen__/graphql.ts

This PR add support for `infoboxBlock` as an extension type in the builtin plugin.

chore(server, web): support infoboxBlock extension type

---

web/src/beta/lib/core/Crust/Infobox/Block/builtin/PropertyList/Content.tsx
web/src/beta/lib/core/Crust/Infobox/Block/builtin/PropertyList/CustomFields/index.tsx
web/src/beta/lib/core/Crust/Infobox/Block/builtin/PropertyList/DefaultFields/index.tsx

chore(web): fix propertylist block not updating on feature change

---

web/src/beta/lib/core/Crust/Infobox/Block/builtin/useExpressionEval.ts
web/src/beta/lib/core/Crust/Infobox/hooks.ts

chore(web): fix infobox blocks using old value when new value is undefined

---

web/src/beta/features/Editor/Visualizer/convert.ts
web/src/beta/features/PublishedVisualizer/convert-new-property.ts
web/src/beta/features/PublishedVisualizer/hooks.ts
web/src/beta/features/PublishedVisualizer/types.ts
web/src/beta/lib/core/mantle/types/index.ts

- Refactor the `newLayers` processing in published-convert file

chore(web): fix sketch layer in published page

---

web/package.json
web/yarn.lock

feat(web): upgrade core

---

web/src/beta/features/Editor/Visualizer/hooks.ts
web/src/beta/features/Editor/Visualizer/index.tsx
web/src/beta/features/Editor/hooks.ts
web/src/beta/features/Editor/index.tsx
web/src/beta/features/Editor/tabs/map/RightPanel/LayerInspector/index.tsx
web/src/beta/features/Editor/tabs/map/RightPanel/index.tsx
web/src/beta/features/Editor/tabs/widgets/Nav/index.tsx
web/src/beta/features/Editor/tabs/widgets/RightPanel/Manager/index.tsx
web/src/beta/features/Editor/tabs/widgets/RightPanel/hooks.ts
web/src/beta/features/Editor/tabs/widgets/RightPanel/index.tsx
web/src/beta/features/Editor/useLayerStyles.ts
web/src/beta/features/Editor/useLayers.ts
web/src/beta/features/Editor/useRightPanel.tsx
web/src/beta/features/Editor/useScene.ts
web/src/beta/features/Editor/useSecondaryNavbar.tsx
web/src/beta/features/Editor/useStorytelling.ts
web/src/beta/features/Visualizer/StoryPanel/Block/builtin/Camera/Content.tsx
web/src/beta/features/Visualizer/StoryPanel/Block/builtin/Camera/Editor/hooks.ts
web/src/beta/features/Visualizer/StoryPanel/Block/builtin/Camera/Editor/index.tsx
web/src/beta/features/Visualizer/StoryPanel/Block/builtin/Camera/index.tsx
web/src/beta/features/Visualizer/shared/types.ts
web/src/beta/pages/EditorPage/index.tsx
web/src/services/state/index.ts

- Update Jotai atoms that used on Beta Editor to local state

chore(web): change beta editor jotai status to local

---

.github/reviewer-lottery.yml

Update the userlist of reviewers.

chore(web): update github reviewers

---

web/src/beta/lib/reearth-ui/components/Button/index.stories.tsx
web/src/beta/lib/reearth-ui/components/Button/index.tsx
web/src/services/theme/reearthTheme/darkTheme/index.ts
web/src/services/theme/reearthTheme/lightTheme/index.ts
web/src/services/theme/reearthTheme/types.ts

- Refactor Button Component based on Figma Design
- Create Button Component
- Didn't create Icon Component

chore(web): implement UI lib Button

---

web/.storybook/preview-head.html
web/src/services/theme/reearthTheme/common/globalStyles.tsx

This PR fixes the font family not applied to button and storybook previews.

chore(web): apply font family on storybook and button

---

web/src/beta/features/Visualizer/Crust/Plugins/hooks.ts

Currently this bind function could be triggered more than once, i added a flag to make sure it only bind once.
Renamed some vars.

chore(web): bind sketch plugin events

---

web/package.json
web/yarn.lock

Using [core v0.0.4](https://github.com/reearth/core/pull/11)

chore(web): update core version

---

web/src/beta/lib/reearth-ui/components/Collapse/index.stories.tsx
web/src/beta/lib/reearth-ui/components/Collapse/index.tsx
web/src/beta/lib/reearth-ui/components/index.ts

chore(web): implement collapse component

---

web/src/beta/lib/reearth-ui/components/Switcher/index.stories.tsx
web/src/beta/lib/reearth-ui/components/Switcher/index.tsx
web/src/beta/lib/reearth-ui/components/index.ts

new component: Switcher
http://localhost:9001/?path=/docs/beta-lib-reearth-ui-components-switcher--docs

chore(web): switcher component

---

web/package.json
web/yarn.lock

chore: upgrade core

---

.github/workflows/release.yml
.github/workflows/stage.yml

Added `--force` option to push to the protected branches.
I'll test this out after merging this PR.

ci: `--force` to push to protected branches

---

.github/workflows/release.yml
.github/workflows/stage.yml

As the title says.
I need to merge this to test this out.

ci: add `--force` option to push to protected branches

---

.github/reviewer-lottery.yml

chore(web): update reviewer

---

web/package.json
web/yarn.lock

chore(web): upgrade @reearth/core

---

web/src/beta/features/PublishedVisualizer/hooks.ts
web/src/beta/features/PublishedVisualizer/index.tsx

chore(web): camera move in published page

---

web/src/beta/lib/reearth-ui/components/Tabs/index.stories.tsx
web/src/beta/lib/reearth-ui/components/Tabs/index.tsx

1. Refactor Tabs to match use cases

chore(web): refactor tabs

---

web/src/beta/lib/reearth-ui/components/Button/index.tsx
web/src/beta/lib/reearth-ui/components/Selector/index.stories.tsx
web/src/beta/lib/reearth-ui/components/Selector/index.tsx
web/src/beta/lib/reearth-ui/components/index.ts

chore(web): implement selector component

---

web/src/beta/ui/fields/ColorField.tsx
web/src/beta/ui/fields/index.ts

chore(web): create color field

---

web/src/beta/ui/fields/SwitchField.tsx
web/src/beta/ui/fields/index.ts

chore(web): create switchfield

---

web/src/beta/features/Visualizer/Crust/Plugins/PluginFrame/PluginIFrame/index.tsx
web/src/beta/features/Visualizer/Crust/Plugins/PluginFrame/SafeIFrame/index.tsx
web/src/beta/features/Visualizer/Crust/Plugins/hooks.ts
web/src/beta/features/Visualizer/Crust/Plugins/types.ts
web/src/beta/features/Visualizer/Crust/Plugins/useExperimentalSandbox.ts
web/src/beta/features/Visualizer/Crust/index.tsx
web/src/beta/features/Visualizer/index.tsx

This PR restrict some rules for plugin iframe, also remved the `useExperimentalSandbox` since we will always use it.

chore(web): restrict sandbox iframe

---

.github/workflows/build_server.yml
.github/workflows/build_web.yml
.github/workflows/ci_docker_build_push.yml
.github/workflows/deploiy_aws.yml
.github/workflows/deploy_server_nightly.yml

Rename Docker image name: `reearth/reearth` -> `reearth/reearth-visualizer`

ci: rename docker image name

---

web/src/beta/features/Editor/Story/PagesPanel/index.tsx
web/src/beta/features/Editor/Story/context.tsx
web/src/beta/features/Editor/hooks/index.ts
web/src/beta/features/Editor/hooks/useLayers.ts

Using ?? [] is leading to some rerender issue somewhere. This PR fixes it.

refactor(web): fix some state updates logic

---

web/src/beta/features/Editor/Map/LayersPanel/LayerItem.tsx
web/src/beta/features/Editor/Map/LayersPanel/index.tsx
web/src/beta/features/Editor/Map/ScenePanel/index.tsx
web/src/beta/lib/reearth-ui/components/TextInput/index.tsx
web/src/beta/ui/components/EntryItem/index.stories.tsx
web/src/beta/ui/components/EntryItem/index.tsx

This PR updates some UX of layer item:
- Always show actions when it's selected.
- Always show eye button when it's hidden.
- Cancel edit state and save value when click aother layer while editing.
Refactor some interface & update story.

chore(web): update some ux of layers item

---

web/src/beta/features/Editor/Map/LayersPanel/LayerItem.tsx

This PR only updates the style of layer title, making it nowrap and hide overflow as expected.

style(web): make layer name nowrap

---

server/gql/project.graphql
server/internal/adapter/gql/generated.go
server/internal/adapter/gql/gqlmodel/convert_project.go
server/internal/adapter/gql/gqlmodel/convert_project_test.go
server/internal/adapter/gql/gqlmodel/models_gen.go
server/internal/adapter/gql/loader_project.go
server/internal/adapter/gql/resolver_mutation_project.go
server/internal/adapter/gql/resolver_query.go
server/internal/adapter/gql/resolver_team.go
server/internal/infrastructure/memory/project.go
server/internal/infrastructure/mongo/mongodoc/project.go
server/internal/infrastructure/mongo/project.go
server/internal/usecase/interactor/project.go
server/internal/usecase/interfaces/project.go
server/internal/usecase/repo/project.go
server/pkg/project/builder.go
server/pkg/project/builder_test.go
server/pkg/project/project.go
server/pkg/project/sort_type.go

This PR adds a few new features required for the new Project Dashboard including Sorting, Starring, Searching.
It also fixes an unexpected bug with `updatedAt` not being updated on every update mutation.

feat(server): add sort, search and starred project functionality

---

web/src/classic/gql/graphql-client-api.tsx
web/src/classic/gql/graphql.schema.json
web/src/services/gql/__gen__/graphql.ts
web/src/services/i18n/translations/en.yml
web/src/services/i18n/translations/ja.yml

Update web `gql` caused by https://github.com/reearth/reearth-visualizer/pull/1040 and yarn i18n

chore(web): update gql and yarn i18n

---

web/package.json

chore: update package version

---

web/vite.config.ts

chore: fix lint error

---

web/src/beta/features/Editor/Map/InspectorPanel/LayerInspector/FeatureInspector/CustomPropertField.tsx
web/src/beta/features/Editor/Map/InspectorPanel/LayerInspector/FeatureInspector/index.tsx
web/src/beta/features/Editor/Map/InspectorPanel/LayerInspector/index.tsx
web/src/beta/features/Editor/Visualizer/convert.ts
web/src/beta/features/Published/convert-new-property.ts
web/src/beta/features/Published/hooks.ts
web/src/beta/features/Published/types.ts
web/src/services/api/layersApi/utils.ts

The process for sketch layer data is incorrect. This PR fixed the process and added the types to avoid using any.
The process

fix(web): sketch data not processed correctly

---

web/src/beta/features/Dashboard/LeftSidePanel/profile.tsx
web/src/beta/features/Dashboard/type.ts
web/src/beta/features/Navbar/index.tsx
web/src/beta/features/Visualizer/Crust/Infobox/Block/builtin/PropertyList/DefaultFields/index.tsx
web/src/beta/features/Visualizer/Crust/Infobox/Block/builtin/Text/index.tsx

This PR:
- Added a shadow on Navbar.
- Refactored the workspace menu to use the same structure in nav bar.
- Fix the height issue on infobox builtin text block.
- Fix the key missing issue on infobox builtin property list block.

refactor(web): update UI on dashboard workspace menu & nav bar & infobox built in blocks

---

.github/workflows/pr.yml

ci: add assign author job on pr actions

---

web/package.json

chore(web): update package version

---

web/src/beta/features/AccountAndWorkSpaceSetting/index.tsx

refactor(web): hide WIP setting pages on tab

---

web/package.json

chore(web): update package version to 1.0.0-alpha.7

---

README.md

chore: update README for docs link

---

web/package.json
web/yarn.lock

Upgraded core version and ran `yarn install`

chore(web): update core version to 0.0.7-alpha.21

---

.github/workflows/build_server.yml

ci: fix tag condition `blank` to empty in build workflow

---

web/package.json
web/yarn.lock

feat(web): update reearth/core

---

web/src/beta/features/PluginPlayground/Plugins/presets/camera/cameraPosition.ts
web/src/beta/features/PluginPlayground/Plugins/presets/camera/cameraRotation.ts
web/src/beta/features/PluginPlayground/Plugins/presets/camera/zoomInOut.ts
web/src/beta/features/PluginPlayground/Plugins/presets/custom/myPlugin.ts
web/src/beta/features/PluginPlayground/Plugins/presets/data/extensionProperty.ts
web/src/beta/features/PluginPlayground/Plugins/presets/data/messengerBetweenExtensions.ts
web/src/beta/features/PluginPlayground/Plugins/presets/data/uiExtensionMessenger.ts
web/src/beta/features/PluginPlayground/Plugins/presets/layerStyles/overrideStyle.ts
web/src/beta/features/PluginPlayground/Plugins/presets/layers/overrideLayerData.ts
web/src/beta/features/PluginPlayground/Plugins/presets/layers/showSelectedFeaturesInformation.ts
web/src/beta/features/PluginPlayground/Plugins/presets/viewer/enableShadowStyle.ts
web/src/beta/features/PluginPlayground/Plugins/presets/viewer/enableTerrain.ts
web/src/beta/features/PluginPlayground/Plugins/presets/viewer/mouseEvent.ts
web/src/beta/features/PluginPlayground/Plugins/presets/viewer/takeScreenshot.ts

fix: refactor custom plugin with new styles

---

.github/workflows/ci_web.yml

ci(web): add job to validate nginx config

---

server/e2e/gql_project_test.go
server/go.mod
server/go.sum
server/internal/usecase/interactor/project.go
server/pkg/alias/check.go
server/pkg/i18n/locales/errmsg/en.json
server/pkg/i18n/locales/errmsg/ja.json
server/pkg/i18n/message/errmsg/errmsg_generated.go

feat(server): validate project alias [VIZ-2047]

---

web/src/app/ui/fields/CameraField/EditorPanel.tsx

fix(web): change camera height unit

---

web/CLAUDE.md
web/src/app/features/RootPage/hooks.ts
web/src/app/features/RootPage/index.tsx
web/src/ee/featureConfig.ts
web/src/ee/features/Welcome/index.tsx
web/src/services/auth/auth0Auth.ts
web/src/services/auth/index.tsx
web/src/services/config/appFeatureConfig.ts

This is no longer needed base on latest setup.

refactor(web): remove externalAuth0Signup feature flag and related logic

---

web/src/services/i18n/translations/ja.yml

fix(web): refactor read me translation

---

web/src/app/features/Dashboard/ContentsContainer/Projects/hooks.ts

Missing property for visibility

fix(web): missing project visibility in project convert

---

server/internal/infrastructure/mongo/migration/250724184601_convert_projectmetadata_id.go
server/internal/infrastructure/mongo/migration/250724184601_convert_projectmetadata_id_test.go

fix(server): migrate projectmetadata id

---

server/internal/infrastructure/mongo/migration/250724191400_copy_team_to_workspace.go
server/internal/infrastructure/mongo/migration/250724191400_copy_team_to_workspace_test.go
server/internal/infrastructure/mongo/migration/migrations.go

fix(server): copy team to workspace

---

server/internal/infrastructure/mongo/migration/250725111952_add_project_alias_2.go
server/internal/infrastructure/mongo/migration/250725111952_add_project_alias_2_test.go
server/internal/infrastructure/mongo/migration/250725112722_metadata_update.go
server/internal/infrastructure/mongo/migration/250725112722_metadata_update_test.go
server/internal/infrastructure/mongo/migration/migrations.go

* There are 9 projects without a projectAlias. These will be updated with default values starting with p-xxx.
* There are 2 project metadata records without an assigned workspace. These will be updated using the workspace associated with their respective projects.

feat(server): Project Data Maintenance

---

server/e2e/gql_asset_test.go
server/e2e/gql_scene_test.go
server/e2e/proto_project_sort_pagination_test.go
server/e2e/proto_project_test.go
server/e2e/proto_project_user_test.go
server/e2e/seeder.go
server/internal/infrastructure/mongo/project.go
server/internal/infrastructure/mongo/scene.go

* The project's visibility is set to public
* The project is not in the trash

fix(server): fix project filtering bug

---

web/package.json

chore(web): Update package version to 1.0.0-beta.8.0

---

server/e2e/proto_project_user_test.go
server/internal/infrastructure/mongo/project_metadata.go

fix(server): project metadata filtering error

---

web/package.json

I will deploy these diff.
https://github.com/reearth/reearth-visualizer/compare/v1.0.0-beta.8.0...main

chore(web): Update package version to 1.0.0-beta.8.1

---

server/internal/adapter/gql/resolver_mutation_project.go
server/internal/adapter/internalapi/server.go
server/internal/app/file_uploader.go
server/internal/usecase/interactor/project.go
server/internal/usecase/interfaces/project.go

- import project -> x 
- private workspace
- private p import -> ok
- public p import -> ok
- public workspace
- **private p import -> x => need to fix this case**
- need to become public project but become private
- public p import -> ok

fix(server): import project data don't set visibility correctly

---

web/package.json

chore(web): bump up version 1.0.0-beta.9.0

---

web/package.json

chore(web): bump up version 1.0.0-beta.9.1

---

web/src/app/features/Editor/Widgets/WidgetManagerPanel/ListItem.tsx

forbidden remove data attribution widget

refactor(web): forbidden remove data attribution widget[VIZ-2139]

---

server/internal/infrastructure/mongo/migration/250820113009_change_esri_to_default.go

refactor(server): refactor migration ChangeEsriToDefault

---

server/internal/infrastructure/mongo/migration/250820113009_change_esri_to_default.go
server/internal/infrastructure/mongo/migration/250820113009_change_esri_to_default_test.go

fix(migration): change esri to default migration

---

web/package.json

bump up version 1.0.0-beta.9.2

chore(web): bump up version 1.0.0-beta.9.2

---

web/package.json

chore(web): bump up version 1.0.0-beta.9.3

chore(web): bump up version 1.0.0-beta.9.3

---

server/e2e/proto_project_export_test.go
server/e2e/proto_project_test.go
server/internal/app/grpc.go
server/internal/infrastructure/mongo/project.go

feat(server): export project without token [VIZ-2212]

---

server/e2e/proto_project_export_test.go
server/e2e/proto_project_test.go
server/internal/adapter/internalapi/server.go
server/internal/app/grpc.go
server/internal/app/grpc_auth_test.go
server/internal/usecase/interactor/project.go

* Public projects allow access without a token/user ID.
* In the case of private, only the owner or members are allowed.

feat(server): exportproject without token2

---

web/src/app.tsx

We have an issue on this extension, temporarily disable it, will re-enable it once extension ready.

refactor(web): temporarily disable global modal

---

web/package.json

chore(web): bump up version to 1.0.0-beta.10.0

---

.github/workflows/ci.yml
e2e/pages/projectScreenPage.ts
e2e/pages/projectsPage.ts
e2e/playwright.config.ts
e2e/tests/dashboard.spec.ts
e2e/tests/login.spec.ts
e2e/tests/projects.spec.ts
web/src/app/features/Dashboard/ContentsContainer/Projects/ProjectCreatorModal.tsx
web/src/app/features/Editor/Map/LayerStylePanel/PresetLayerStyle/index.tsx
web/src/app/ui/fields/InputField/index.tsx
web/src/app/ui/fields/SelectField/index.tsx
web/src/app/ui/fields/TextareaField/index.tsx

test(web): fixed e2e tests and enable ci/cd

---

server/internal/adapter/gql/gqlmodel/convert_project.go

fix(server): fix export project prop

---

server/e2e/gql_project_export_test.go
server/e2e/gql_project_import_signature_test.go
server/e2e/gql_project_import_split_test.go
server/pkg/file/zip.go

feat(server): add split-import test

---

server/internal/usecase/interactor/project.go

fix(server): debug log

---

server/internal/usecase/interactor/project.go

fix(server): delete debug code
