reearth/reearth-visualizer

server/pkg/builtin/manifest.yml, server/pkg/builtin/manifest_ja.yml
OSM Buildings is a 3D buildings layer covering the entire world. It's available as a 3D Tileset on Cesium.
we modified reearth back end in  way that allows the user to add OSM building 3d Tileset as a layer in his project by providing him with an interface to chose which tiles to show on the map.
- modify manifes.yml and add the new attributes related to 3D OSM building tiles.
- add the Japanese translation to manifest.ja.yml 
https://www.figma.com/file/bdnfDaGXGoNfUws4y7JItl/Re%3AEarth-UI-Gamma?node-id=11576%3A179143
=> feat(server): add 3D OSM building tiles

server/internal/app/config.go, server/internal/app/repo.go, server/internal/infrastructure/marketplace/marketplace.go, server/internal/infrastructure/marketplace/marketplace_test.go, server/internal/usecase/gateway/plugin_registry.go, server/internal/usecase/interactor/plugin_common.go
=> feat(server): notify plugin donwload to marketplace

server/pkg/builtin/manifest.yml, server/pkg/builtin/manifest_ja.yml
- Added manifest for navigator builtin widget 
see https://github.com/reearth/reearth-web/pull/323
=> feat(server): add builtint navigator widget manifest

server/pkg/builtin/manifest_ja.yml
=> fix(server): Japanese typo error

server/pkg/builtin/manifest.yml, server/pkg/builtin/manifest_ja.yml
=> feat(server): Add Visible field to built-in widgets

server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqldataloader/workspaceloader_gen.go, server/internal/adapter/gql/gqlmodel/convert_scene_align.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/internal/infrastructure/mongo/mongodoc/scene_align.go, server/internal/usecase/interactor/scene.go, server/pkg/scene/builder/encoder.go, server/pkg/scene/builder/scene_test.go, server/pkg/scene/widget_area.go, server/pkg/scene/widget_area_test.go, server/pkg/scene/widget_section.go, server/schema.graphql
regarding the padding default value I did the following changes:
- `padding` object is nil if not set
- `gap` is declared as a pointer
=> fix(server): make widget area gap optional

server/pkg/property/sealed_test.go, server/pkg/property/value_dataset.go, server/pkg/property/value_dataset_test.go
the new condition:
- if datast value is not nil and the property value is nil -> fetch the dataset value
- otherwise fetch property value
=> fix(server): prefer dataset values when merging properties

.github/workflows/ci_collect_info.yml, .github/workflows/ci_server.yml, .github/workflows/ci_web.yml
This PR add conditional check on `ci-web` and `ci-server` to avoid triggering their workflow's job if the commit is created by renovate.
=> chore(ci): add conditional in ci-web and ci-server for renovate commits

web/src/core/engines/Cesium/Feature/index.tsx
This PR fixes an issue observed with layers with features in them like e.g geojson where the show/hide feature wasn't functional.
=> fix(web): feature containing layer show hide not working

.github/workflows/ci_collect_info.yml, .github/workflows/ci_server.yml, .github/workflows/ci_server_build.yml, .github/workflows/ci_web.yml, .github/workflows/ci_web_build.yml
This PR adds `release` as one of the possible branches in `ci` workflows.
=> ci: add release in the ci release flow

web/src/components/molecules/Visualizer/hooks.ts
For classic layer system, infobox should only shown when user added an infobox to the layer.
Currently when select a 3d tiles the overriden infobox will show up, which is not the expected behavior.
Show classic infobox only when selected layer has infobox.
- Test in local.
- Test in plugin editor with:
```js
reearth.layers.add({
extensionId: "tileset",
isVisible: true,
title: `3D Tiles`,
property: {
default: {
tileset: 'https://assets.cms.plateau.reearth.io/assets/11/6d05db-ed47-4f88-b565-9eb385b1ebb0/13100_tokyo23-ku_2022_3dtiles%20_1_1_op_bldg_13101_chiyoda-ku_lod1/tileset.json'
},
},
// infobox: {
//   blocks:[],
//   property:{
//     default:{
//       title: '3D Tiles Infobox'
//     }
//   }
// },
});
```
=> fix(web): classic infobox always shown for 3d tiles

web/src/components/organisms/Dashboard/hooks.ts, web/src/components/organisms/EarthEditor/Header/hooks.ts, web/src/components/organisms/Settings/SettingPage/hooks.ts, web/src/components/organisms/Settings/Workspace/hooks.ts
When user create a new workspace it doesn't save in session , so when he opens a new tabs the last workspace is returned wrongly
=> fix(web): create new workspace doesn't save session

netlify.toml
This PR temporarily removes `netlify.toml` file temporarily from the root.
=> chore: remove netlify.toml

web/src/auth/provider.tsx
Reference [here](https://community.auth0.com/t/auth0-spa-2-x-returning-missing-refresh-token/98999/15).
- Fix: add `useRefreshTokensFallback` to `Auth0Provider` authorizationParams.
- Rename `redirectUri` to `redirect_uri`: the old naming is going to be removed in the future base on auth0 doc.
=> fix(web): auth0 error when refresh token

.github/workflows/ci_web.yml, web/.eslintignore, web/.storybook/preview.tsx, web/package.json
This PR solves these problems.
- `yarn eslint` will freeze while it's running.
- Compared to old repository, there are some missing file
- `lint-staged` does not catch any staged files when running git-hook
- Add eslintignore
- Old repository had ignored `graphql-client-api.tsx` which is the cause of the freezing problem
- https://github.com/reearth/reearth-web/blob/main/.eslintignore#L8
- Add CI task
- Old repository had the task in CI
- https://github.com/reearth/reearth-web/blob/main/package.json#L18
- https://github.com/reearth/reearth-web/blob/main/.github/workflows/ci.yml#L32
- Fix `lint-staged` setting
Manually run `yarn lint` and `yarn lint-staged` in my local.
CI will be displayed in this PR.
=> ci: fix git hook, ESLint and CI setting to work properly

web/.storybook/preview.tsx
I've done the following improvement for Storybook preview setting.
- Use explicit typing
- Use `argTypesRegex` in default. We don't need to set it in every Storybook definition.
=> chore(web): improve storybook preview setting

.github/workflows/ci.yml
This PR fixes skipped workflow issue faced in https://github.com/reearth/reearth/actions/runs/5200171904
=> ci: fix build deadlock after ci finishes

.github/workflows/ci.yml
The repository_dispatch action does not support triggering workflow on a custom branch, see https://github.com/peter-evans/repository-dispatch/issues/39#issuecomment-671657524. We can't test this before the release but it should work. We need to trigger the workflow from the next branch since it differs from the main one. Another approach would be merging the next workflow to main, but that is confusing and harder to maintain.
=> ci(web): use workflow-dispatch action to trigger next branch workflow

.github/workflows/build_server.yml, .github/workflows/build_web.yml, .github/workflows/ci.yml
This PR fixes an issue observed with tags being "[blank](https://github.com/reearth/reearth/blob/653523ddbdf2aa1da940bc1d0864818d279156bb/.github/workflows/ci.yml#L59)" instead of null or undefined value. 
ref: https://github.com/reearth/reearth/actions/runs/5212511263/jobs/9406193403
=> ci(web, server): fix blank/null value issue with info

web/src/beta/lib/core/engines/Cesium/CustomShaders/NonPBRLightingShader.ts, web/src/beta/lib/core/engines/Cesium/Feature/Model/index.tsx, web/src/beta/lib/core/engines/Cesium/Feature/Tileset/index.tsx, web/src/beta/lib/core/mantle/types/appearance.ts
CustomShader: https://cesium.com/learn/cesiumjs/ref-doc/CustomShader.html
The original implementation: https://github.com/takram-design-engineering/plateau-view/blob/00fc34eda3d0b22eb7a115a948a6901f0926f860/libs/datasets/src/LambertDiffuseShader.ts#L8
|PBR|Non PBR|
|:--:|:--:|
|![Screenshot 2023-06-23 at 16 39 01](https://github.com/reearth/reearth/assets/34934510/716d3b0e-a621-4fe8-b95a-973d10448054)|![Screenshot 2023-06-23 at 16 46 56](https://github.com/reearth/reearth/assets/34934510/67cc3f43-c0ea-4861-b5b1-ad904bbf0770)|
- Added `pbr` property to `3dtiles` and `model` appearance.
1. Add 3dtiles as follow
```
reearth.layers.add({
data: {
url: "https://assets.cms.plateau.reearth.io/assets/4f/702958-5009-4d6b-a2e0-157c7e573eb2/13100_tokyo23-ku_2022_3dtile …
```
=> feat(web): add an option to disable default PBR to 3dtiles and model features in NLS

web/src/beta/features/Navbar/hooks.ts, web/src/classic/components/organisms/Authentication/RootPage/hooks.ts, web/src/classic/components/organisms/Dashboard/hooks.ts, web/src/classic/components/organisms/EarthEditor/Header/hooks.ts, web/src/classic/components/organisms/EarthEditor/PropertyPane/hooks.ts, web/src/classic/components/organisms/Settings/Account/hooks.ts, web/src/classic/components/organisms/Settings/Project/Dataset/hooks.ts, web/src/classic/components/organisms/Settings/Project/Public/hooks.ts, web/src/classic/components/organisms/Settings/Project/hooks.ts, web/src/classic/components/organisms/Settings/ProjectList/hooks.ts, web/src/classic/components/organisms/Settings/SettingPage/hooks.ts, web/src/classic/components/organisms/Settings/Workspace/Asset/hooks.ts, web/src/classic/components/organisms/Settings/Workspace/hooks.ts, web/src/classic/components/pages/Authentication/hooks.ts, web/src/services/state/index.ts
We were getting an infinite loop on the Dashboard that was hurting the server (probably).
The logic around remembering the previous workspace was hard to understand and maintain, so I decided to remove that implementation so we can get Re:Earth back to a working condition and then reimplement that functionality later.
=> fix(web): revert functionality to remember last workspace opened

web/src/services/gql/provider.tsx
An infinite loop would happen on an Apollo Client networking error. Turns out this was due to using Jotai state inside our GQL provider for the error message to be shown in our Notification component.
- Fixed the infinite loop
- We lose user-facing error messages for GQL (both networking errors and gql errors, which includes policy errors). This PR doesn't include adding error handling directly in the components whose query/mutation can cause these sorts of errors.
Later need to create an error handling policy around GQL and implement it on each query/mutation
=> fix(web): infinite loop on network error

web/src/beta/lib/core/Map/types/index.ts, web/src/beta/lib/core/engines/Cesium/hooks.ts
Add shadow map support for beta.
add:
```ts
type SceneProperty = {
atmosphere?: {
// ...
shadowResolution?: 1024 | 2048 | 4096,
softShadow?: boolean,
shadowDarkness?: number,
};
};
```
```js
let layerId = reearth.layers.add({
data: {
url: "https://assets.cms.plateau.reearth.io/assets/11/6d05db-ed47-4f88-b565-9eb385b1ebb0/13100_tokyo23-ku_2022_3dtiles%20_1_1_op_bldg_13101_chiyoda-ku_lod1/tileset.json",
},
"3dtiles": {
pbr: false
}
});
setTimeout(()=>{
reearth.camera.flyTo(layerId);
reearth.scene.overrideProperty({
atmosphere:{
shadows: true,
shadowResolution: 4096,
softShadow: true,
shadowDarkness: 0.3
},
terrain:{
terrain: true,
}
});
},0);
```
=> feat(web): visualizer supports shadow map

server/.goreleaser.yml
This PR refactor `goreleaser.yml` as it utilizes depreciated method like `replacements` for name_template.
ref: https://goreleaser.com/deprecations/#expired-deprecation-notices_1
=> ci(server): update goreleaser.yml, remove depreciated methods

server/.env.example
Setting AssetBaseURL config value is necessary in order to run a custom domain server.
I added the corresponding REEARTH_ASSETBASEURL environment variable to `/server/.env.example`, to avoid future confusion.
=> chore(server): Add REEARTH_ASSETBASEURL to /server/.env.example

server/internal/infrastructure/mongo/asset.go, server/internal/infrastructure/mongo/dataset.go, server/internal/infrastructure/mongo/dataset_schema.go, server/internal/infrastructure/mongo/layer.go, server/internal/infrastructure/mongo/mongodoc/asset.go, server/internal/infrastructure/mongo/mongodoc/consumer.go, server/internal/infrastructure/mongo/mongodoc/dataset.go, server/internal/infrastructure/mongo/mongodoc/dataset_schema.go, server/internal/infrastructure/mongo/mongodoc/layer.go, server/internal/infrastructure/mongo/mongodoc/plugin.go, server/internal/infrastructure/mongo/mongodoc/project.go, server/internal/infrastructure/mongo/mongodoc/property.go, server/internal/infrastructure/mongo/mongodoc/property_schema.go, server/internal/infrastructure/mongo/mongodoc/scene.go, server/internal/infrastructure/mongo/mongodoc/tag.go, server/internal/infrastructure/mongo/mongodoc/tag_test.go, server/internal/infrastructure/mongo/mongodoc/user.go, server/internal/infrastructure/mongo/mongodoc/workspace.go, server/internal/infrastructure/mongo/plugin.go, server/internal/infrastructure/mongo/project.go, server/internal/infrastructure/mongo/project_test.go, server/internal/infrastructure/mongo/property.go, server/internal/infrastructure/mongo/property_schema.go, server/internal/infrastructure/mongo/scene.go, server/internal/infrastructure/mongo/tag.go, server/internal/usecase/repo/container.go, server/internal/usecase/repo/container_test.go, server/pkg/tag/group_builder.go
Filter documents in server instead of mongo
=> fix(server): reduce size of queries sent to MongoDB

web/src/classic/components/molecules/Visualizer/index.tsx, web/vite.config.ts
- Fixed the problem that OSM building is not displayed.
- Fixed to be able to set Cesium ion token in local easily.
```sh
CESIUM_ION_ACCESS_TOKEN="ION_TOKEN" yarn start
```
=> fix(web): pass ion token to each layer

web/vite.config.ts
You can specify the remote reearth config through an environment variable for development in local env.
```
REEARTH_WEB_CONFIG_URL="URL for ReEarth config"
```
=> chore(web): allow reearth_config.json to be set remotely for local development

web/src/beta/lib/core/Map/types/index.ts, web/src/beta/lib/core/engines/Cesium/hooks.ts
Add antialias options to scene property (for beta).
I added `render.antialias` since all scene properties are organized by groups.
```ts
type SceneProperty = {
// ...
render?: {
// low: msaaSamples = 1
// medium: msaaSamples = 4
// heigh: enable fxaa
// extreme: msaaSamples = 8
antialias: "low" | "medium" | "high" | "extreme";
}
};
```
```js
let layerId = reearth.layers.add({
data: {
url: "https://assets.cms.plateau.reearth.io/assets/11/6d05db-ed47-4f88-b565-9eb385b1ebb0/13100_tokyo23-ku_2022_3dtiles%20_1_1_op_bldg_13101_chiyoda-ku_lod1/tileset.json",
},
"3dtiles": {
pbr: false
}
});
setTimeout(()=>{
reearth.camera.flyTo(layerId);
},0);
```
```js
reearth.scene.overrideProperty({
render: {
antialias: "medium"
}
})
```
=> feat(web): visualizer antialiasing

web/src/classic/components/organisms/EarthEditor/CanvasArea/convert.ts
This PR attempts to remove duplication of layer and RawLayer from cavasArea's `convert.ts` file which is causing type errors.
=> chore(web): remove duplication from canvas convert.ts

.github/workflows/build_web.yml, .github/workflows/ci.yml
This PR attempts to fix an issue observed with `build-web` action failing due to lack of memory.
=> ci(web): increase old-space-size for Node in build-web

web/src/beta/features/Editor/Visualizer/CanvasArea/hooks.ts, web/src/beta/features/Editor/Visualizer/CanvasArea/index.tsx, web/src/beta/lib/core/Map/types/index.ts, web/src/beta/lib/core/README.md, web/src/beta/lib/core/Visualizer/context.tsx, web/src/beta/lib/core/Visualizer/hooks.ts, web/src/beta/lib/core/Visualizer/index.stories.tsx, web/src/beta/lib/core/Visualizer/index.tsx, web/src/beta/lib/core/engines/Cesium/hooks.ts, web/src/beta/lib/core/engines/Cesium/index.tsx
I added VisualizerContext API to access to the API of the Visualizer.
You can access like this.
```tsx
const visualizer = useVisualizer();
visualizer.current?.engine.flyTo({
lat: 35.683252649879606,
lng: 139.75262379931652,
height: 5000,
});
visualizer.current?.layers.add({
data: {
type: "geojson",
value: {
// GeoJSON
type: "Feature",
geometry: {
coordinates: [139.75262379931652, 35.683252649879606, 1000],
type: "Point",
},
},
},
marker: {
imageColor: "blue",
},
});
```
- Added VisualizerContext API
- Added onMount props to Visualizer
1. Go to storybook on preview
2. Move to `?path/story/beta-lib-core-visualizer--api`
3. Set the Cesium token to `meta` props on the bottom bar in storybook
```
{
"cesiumIonAccessToken": …
```
=> feat(web): add VisualizerContext in NLS for beta

web/src/beta/lib/core/engines/Cesium/PostProcesses/hbao/AmbientOcclusion.tsx, web/src/beta/lib/core/engines/Cesium/PostProcesses/hbao/createAmbientOcclusionStage.ts, web/src/beta/lib/core/engines/Cesium/PostProcesses/hbao/createCrossBilateralFilterStage.ts
I fixed the bug which crushes the application when we enable the ambient occlusion feature.
I fixed to use `cesium` library from `@cesium/engine`. Because Cesium can not share the state when using different library.
=> fix(web): crash app by ambient occlusion

web/src/services/config/unsafeBuiltinPlugin.ts
Re:Earth is logged out when built-in plugin load is failed. So I fixed to suppress the error.
=> fix(web): suppress error in loading built-in plugin

server/e2e/common.go, server/internal/app/config/config.go, server/internal/app/repo.go, server/internal/infrastructure/mongo/container.go, server/internal/usecase/interactor/dataset.go, server/internal/usecase/interactor/layer.go, server/internal/usecase/repo/container.go
Add an env var (REEARTH_DB_ACCOUNT) to specify the database name for accounts, separate from the regular database
=> feat(server): add env var to specify account database

web/src/beta/lib/lexical/RichTextEditor/index.css, web/src/beta/lib/lexical/RichTextEditor/index.tsx, web/src/beta/lib/lexical/RichTextEditor/themes/DefaultLexicalEditorTheme.css, web/src/beta/lib/lexical/RichTextEditor/ui/ColorPicker.css, web/src/beta/lib/lexical/RichTextEditor/ui/Input.css
Add `.lexical` to lexical component to avoid style pollution.
Also move float link editor into editor DOM for better organization.
=> chore(web): limit lexical css

web/src/beta/lib/core/Map/Layers/hooks.ts
I noticed this script doesn't work due to layers are deleted unexpectedly when Visualizer's `layer` prop is updated. 
```
const id = reearth.layers.add({
data: {
url: "https://assets.cms.plateau.reearth.io/assets/ca/ee4cb0-9ce4-4f6c-bca1-9c7623e84cb1/13100_tokyo23-ku_2022_3dtiles_1_1_op_bldg_13101_chiyoda-ku_lod2_no_texture/tileset.json"
},
"3dtiles": {},
})
setTimeout(() => {
reearth.camera.flyTo(id);
}, 100);
```
=> chore(web): fix the layer delete behavior

web/src/beta/components/fields/PropertyFields/index.tsx, web/src/beta/components/fields/TextField/index.stories.tsx, web/src/beta/components/fields/TextField/index.tsx, web/src/beta/components/fields/common/TextInput/index.stories.tsx, web/src/beta/components/fields/common/TextInput/index.tsx, web/src/beta/features/Editor/tabs/widgets/RightPanel/ContainerSettings/index.tsx, web/src/beta/features/ProjectSettings/innerPages/GeneralSettings/index.tsx, web/src/beta/features/ProjectSettings/innerPages/PluginSettings/PluginInstall/PublicRepo/index.tsx, web/src/beta/features/ProjectSettings/innerPages/PublicSettings/PublicSettingsDetail.tsx
Refactoring the  text input , to two separate component text input and text field.
=> refactor: refactor text input component

web/src/beta/lib/core/engines/Cesium/useOverrideGlobeShader.ts
In VIEW3.0, application is crashed when back to the dashboard while HBAO is enabled. So I fixed this error.
=> chore(web): fix HBAO error when Cesium is destroyed

web/src/beta/features/Editor/DataSourceManager/DelimitedText/index.tsx
This fixes a small issue around the Delimited layer type `csv` in Beta's Data Source Manager. Where the input type of `longitude` and `latitude` was made `number` instead of `text`.
=> chore(web): fix delimited layer input field type

web/src/beta/components/fields/SelectField/index.stories.tsx, web/src/beta/components/fields/SelectField/index.tsx
- Select field minor fixes
- added z-index 
- added reverting arrow icon 
- fixed height 
- added placeholder prop
NA
- Stories 
NA
NA
=> chore(web): Select field - Minor fixes

web/src/beta/features/Editor/Visualizer/hooks.ts, web/src/beta/lib/core/StoryPanel/Block/index.tsx, web/src/beta/lib/core/StoryPanel/Block/types.ts, web/src/beta/lib/core/StoryPanel/Page/BlockAddBar.tsx, web/src/beta/lib/core/StoryPanel/Page/index.tsx
Add missing params `pageId` on create and remove story block.
=> chore(web): fix create & remove story block

web/src/beta/components/fields/URLField/index.tsx, web/src/beta/features/Assets/constants.ts, web/src/services/i18n/translations/en.yml, web/src/services/i18n/translations/ja.yml
This PR is to remove the video format verification as not all video URL should have same video format.
=> fix(web): remove video URL format verification

web/src/beta/lib/core/engines/Cesium/hooks.ts
FXAA is not working with alpha, so it was disabled for now.
=> chore(web): disable fxaa

server/go.mod, server/go.sum, server/internal/app/auth_client.go, server/internal/usecase/interactor/common.go, server/internal/usecase/interactor/policy.go
- The number of members of workspaces was not limited by policy. It was fixed.
- Fixed workspace to correctly use default policy.
=> fix(server): workspace member count is not limited by policies

web/src/beta/lib/core/Map/Layers/hooks.ts, web/src/beta/lib/core/engines/Cesium/useEngineRef.ts, web/src/services/api/widgetsApi/utils.ts
This PR:
- Allows show installed widgets.
- Fixs the computed feature property.
- Comment the setting id for legacy layer to avoid crash.
**THIS IS REQUIRED FOR SHOW CASE.**
=> chore(web): show installed widgets & fix computed feature property

web/src/beta/features/Editor/DataSourceManager/Asset/index.tsx
define the asset type as "file" so the asset modal only shows file types in data source manager.
=> chore: add asset type to data source manager

web/src/beta/lib/core/engines/Cesium/hooks.ts, web/src/beta/lib/core/engines/Cesium/pickMany.ts, web/src/beta/lib/core/engines/Cesium/utils.ts
Fix bugs around feature selection.
- Fix selection indicator to hide in correct step
- Fix pickManyFromViewport
- Fix property conversion for each feature.
=> chore(web): fix some bugs around feature selection functionality

web/src/beta/components/fields/URLField/index.tsx, web/src/beta/hooks/useAssetUploader/hooks.tsx
When user presses on upload file , we customized what are the allowed extensions that he can upload them.
=> chore(web): customize file extension in upload file's window

web/src/beta/lib/core/engines/Cesium/useEngineRef.ts, web/src/beta/lib/core/engines/Cesium/utils.ts
In previous flyTo, this had searched all 3dtiles's features. However 3dtiles's feature can't flyTo automatically by Cesium. So we don't need to search it for flyTo. Therefore I fixed to skip the search process in flyTo.
=> chore(web): improve performance of flyTo

server/pkg/builtin/manifest.yml, server/schemas/plugin_manifest.json
This PR adds support for `collection` which contains the name for accumulated collection parent name of a bunch of schemaGroups together.
=> chore(server): update manifest and plugin_schema to support collection in schemaGroup

web/src/beta/utils/value.ts
This is PR updates the `DEFAULT_LAYER_STYLE`  utilised in converting the received layer from the backend to the visualizer processable format in Visualizer's `convert.ts`.
`"3dtiles"` default property has been added as `show: true` and `heightReference` has been set to 'clamp' for the `model` and `ellipsoid`.
=> chore(web): update default layer style

web/src/beta/utils/value.ts
This PR fixes an issue observed when performing flyTo on a layer in Beta.
Its was produced by this [PR](https://github.com/reearth/reearth/pull/754).
=> chore(web): fix flyTo giving error in beta

server/pkg/builtin/manifest.yml
This adds Play Mode to Timeline Settings Story Block. With default value as `once` and choices given between `once` and `loop`.
=> chore(server): add play mode to timeline setting in manifest

web/src/beta/components/Popover/hooks.ts, web/src/beta/components/Portal/index.tsx, web/src/beta/features/Editor/DataSourceManager/Common/index.tsx, web/src/beta/features/Editor/DataSourceManager/DelimitedText/index.tsx, web/src/beta/features/Editor/DataSourceManager/ThreeDTiles/index.tsx, web/src/beta/lib/lexical/RichTextEditor/ui/DropDown.tsx
This is a small refactor PR which attempts to make consistent way of import React related function into Beta. quick example being `useState` and `useMemo`.
=> chore(web): add consistency to react imports

web/src/beta/features/Editor/DataSourceManager/VectorTiles/index.tsx
This PR fixes an oversight made with https://github.com/reearth/reearth/pull/706 which lead to MVT layer adding behaviour not being on par.
=> chore(web): fix mvt layer behaviour

web/src/beta/features/Editor/DataSourceManager/Common/index.tsx
This PR fixes an issue observed with CZML and KML data now showing up when added as a value in Beta DataSourceManager.
Due to underlying reason being, when resource based data is added as local value, it requires to passed into the the `url` field of the layer instead of value.
=> chore(web): czml and kml local not working

web/src/beta/components/fields/URLField/index.tsx, web/src/beta/features/Editor/DataSourceManager/Common/index.tsx, web/src/beta/features/Editor/DataSourceManager/DelimitedText/index.tsx, web/src/beta/features/Editor/DataSourceManager/utils.tsx, web/src/beta/features/Modals/AssetModal/index.tsx
This PR fixes an issue observed with layerName when layer data is being added by local method i.e assets.
=> chore(web): fix local name is random when added through asset

web/src/beta/lib/core/engines/Cesium/Feature/Marker/index.tsx, web/src/beta/lib/core/mantle/types/appearance.ts
This PR adds support for `height` as a possible parameter for marker's appearance. After this change the user can directly add and adjust `height` through the style code.
=> chore(web): add height to marker appearance

web/src/beta/components/SidePanelSectionField/index.tsx, web/src/beta/features/Editor/Visualizer/hooks.ts, web/src/beta/features/Editor/index.tsx, web/src/beta/features/Editor/useLayerStyles.ts, web/src/beta/features/Editor/useScene.ts, web/src/beta/lib/core/StoryPanel/Page/hooks.ts, web/src/beta/lib/core/StoryPanel/Page/index.tsx, web/src/beta/lib/core/StoryPanel/constants.ts, web/src/beta/lib/core/StoryPanel/utils.ts, web/src/services/state/index.ts
=> chore(web): misc bug fixes improvements

web/src/beta/features/Notification/hooks.ts, web/src/beta/features/Notification/index.tsx
- Moves notification's to the middle of the screen, away from user actions. It is kept a bit higher so that it doesn't get in the way of the visualizer. But also not so high it becomes part of the navbar
- Cleans up the UI. Shows the cancel button only on hover. Rounded corners.
- Updates UX. Shows notifications for shorter time, but if you hover over the notification it'll persist until you stop hovering
=> chore(web): new beta notification

web/src/beta/components/SidePanelSectionField/index.tsx, web/src/beta/features/Editor/tabs/map/LeftPanel/GroupField/index.tsx
Make sure side panels are collapse at first render
=> chore(web): collapse side panels

web/src/beta/lib/core/StoryPanel/ActionPanel/index.tsx, web/src/beta/lib/core/StoryPanel/Page/hooks.ts
- Fix the gap field component in page action panel , moving from this 
To this 
- Fix  the unique key warning
=> chore(web): fix gap field component

web/src/beta/features/Editor/tabs/map/BottomPanel/LayerStyleCard.tsx, web/src/beta/features/Editor/tabs/map/LeftPanel/Layers/LayerItem.tsx
This PR changes the behaviour to editing the layerName on the leftPanel from SHIFT+Click to DoubleClick to go on editing mode and fix misfiring of single click when attempting to make a doubleClick by introducing debouncing in both LayerItem and LayerStyleCard component.
=> chore(web): handle misfiring of singleClick on doubleClick at layerName and layerStyleName

web/src/beta/features/Editor/tabs/map/BottomPanel/LayerStyleCard.tsx, web/src/beta/features/Editor/tabs/map/LeftPanel/Layers/LayerItem.tsx, web/src/beta/utils/use-double-click.ts
This PR moves the logic used for handle doubleClicks in `layerStyleCard` and `layerItem` to a general hook called `useDoubleClick` in utils.
=> chore(web): move doubleClick with debounce to utils

web/src/beta/lib/core/Map/Layers/hooks.ts
The [selected feature color](https://github.com/reearth/reearth/blob/770edb9abe80d917876dcc4e08bb2f4df62a645a/web/src/beta/lib/core/mantle/types/appearance.ts#L149) wasn't updated to default color when I select nothing(click base-map). So I fixed this issue.
1. Click some 3dtile's feature in VIEW3.0 plugin
2. Then the color of model should be changed.
3. Click base-map
4. Then the color of model should be default color.
=> chore(web): fix feature unselection

web/src/beta/lib/core/engines/Cesium/Feature/Marker/index.tsx, web/src/beta/lib/core/engines/Cesium/Feature/Model/index.tsx, web/src/beta/lib/core/engines/Cesium/Feature/Polygon/index.tsx, web/src/beta/lib/core/engines/Cesium/Feature/Polyline/index.tsx
In VIEW3.0, marker isn't updated until camera is moved after changing color.
So I fixed to invoke requestRender in primitive features like marker, polyline and polygon whenever the each feature component is updated.
=> fix(chore): invoke requestRender in primitive features whenever component is updated

web/src/beta/lib/core/engines/Cesium/Feature/Resource/index.tsx, web/src/beta/lib/core/engines/Cesium/Feature/Resource/utils.ts, web/src/beta/lib/core/engines/Cesium/Feature/Tileset/hooks.ts, web/src/beta/lib/core/engines/Cesium/pickMany.ts, web/src/beta/lib/core/engines/Cesium/useEngineRef.ts, web/src/beta/lib/core/engines/Cesium/utils.ts, web/src/beta/lib/core/mantle/types/index.ts
I added this to display the description on VIEW3.0 feature inspector. 
Run this script to test this PR.
```
const layerId = reearth.layers.add({
data: {
type: "czml",
url: "https://d2jfi34fqvxlsc.cloudfront.net/main/data/czml/landmark/01100_sapporo/hospital.czml"
},
marker: {
}
});
setTimeout(() => reearth.camera.flyTo(layerId), 10);
console.log(reearth.layers.layers[0].computed.features); // You can see that each feature has the description.
```
=> chore(web): add an API to get description from entity

web/src/beta/components/Popover/index.tsx, web/src/beta/components/fields/SelectField/index.tsx, web/src/beta/components/fields/common/TextInput/index.tsx, web/src/beta/features/Editor/DataSourceManager/Common/index.tsx, web/src/beta/features/Editor/index.tsx, web/src/beta/features/Navbar/index.tsx, web/src/beta/features/Navbar/useRightSection.tsx, web/src/beta/hooks/navigationHooks.ts, web/src/beta/lib/core/StoryPanel/ActionPanel/index.tsx, web/src/beta/lib/core/StoryPanel/Page/index.tsx, web/src/beta/lib/core/StoryPanel/PanelContent/hooks.ts, web/src/beta/lib/core/StoryPanel/PanelContent/index.tsx, web/src/beta/lib/core/StoryPanel/hooks.ts, web/src/beta/lib/core/StoryPanel/hooks/useElementOnScreen.tsx, web/src/beta/lib/core/StoryPanel/index.tsx
Until now, even if you change tabs (from publish to story, or vice versa), the currently scrolled position of the StoryPanel remained. Instead of this, its more desirable to reset the storypanel.
=> chore(web): reset current page on tab change

web/src/beta/lib/core/engines/Cesium/Feature/Marker/index.tsx, web/src/classic/core/engines/Cesium/Feature/Marker/index.tsx
This PR fixs the check for coordinates height of marker extrudePoints in both classic core and beta core.
=> fix(web): core marker extrude check for coordinates height

web/src/beta/features/PublishedVisualizer/hooks.ts
This PR fixes the issue that padding value `0` will be ingored in published WAS area.
=> chore(web): fix published WAS area padding

web/src/beta/lib/core/Crust/index.tsx, web/src/beta/lib/core/Map/Layers/hooks.ts, web/src/beta/lib/core/Map/index.tsx, web/src/beta/lib/core/engines/Cesium/Feature/Frustum/FrustumColorAppearance.ts, web/src/beta/lib/core/engines/Cesium/Feature/Frustum/getFieldOfView.ts, web/src/beta/lib/core/engines/Cesium/Feature/Frustum/index.stories.tsx, web/src/beta/lib/core/engines/Cesium/Feature/Frustum/index.tsx, web/src/beta/lib/core/engines/Cesium/Feature/Frustum/shaders/frustumAppearance.frag.glsl, web/src/beta/lib/core/engines/Cesium/Feature/Frustum/shaders/frustumAppearance.vert.glsl, web/src/beta/lib/core/engines/Cesium/Feature/index.tsx, web/src/beta/lib/core/engines/Cesium/Feature/utils.tsx, web/src/beta/lib/core/engines/Cesium/hooks.ts, web/src/beta/lib/core/engines/Cesium/useEngineRef.ts, web/src/beta/lib/core/engines/Cesium/utils.ts, web/src/beta/lib/core/mantle/types/appearance.ts
I added frustum model.
Used for this one for VIEW3.0.
- Added frustum appearance and feature component
- Support flyTo for frustum
- Select frustum feature
- Show indicator when selecting, it's impossible due to Cesium doesn't support selecting Primitive.
```js
const id = reearth.layers.add({
data: {
type: "geojson",
value: {
type: "Feature",
geometry: {
type: "Point",
coordinates: [0, 0, 1000],
},
},
},
frustum: {
zoom: 1,
color: "#00ff00",
length: 10000,
},
});
setTimeout(() => reearth.camera.flyTo(id), 100);
```
=> chore(web): add frustum model

web/src/beta/lib/core/engines/Cesium/Feature/HeatMap/index.tsx
This PR fixes a bug produced by `HeatMap` component when camera is being moved is scene becomes `undefined`.
=> chore(web): fix scene undefined bug in heatmap

web/src/beta/lib/core/engines/Cesium/Shaders/CustomShaders/NonPBRLightingShader.ts
Before this change, texture was disappear when disabling PBR. So I fixed this issue.
|Non-PBR with texture|PBR with texture|
|:--:|:--:|
|![Screenshot 2024-01-22 at 13 08 09](https://github.com/reearth/reearth/assets/34934510/078cc224-1958-459b-bd20-893e4e31bce0)|![Screenshot 2024-01-22 at 13 08 37](https://github.com/reearth/reearth/assets/34934510/935ece90-e381-4b47-a96b-e24ef5d0930e)|
```js
const id = reearth.layers.add({
data: {
url: "https://assets.cms.plateau.reearth.io/assets/e3/a75ee8-6621-48d4-97ee-d38d10b23677/13100_tokyo23-ku_2022_3dtiles_1_2_op_bldg_13101_chiyoda-ku_lod2/tileset.json",
},
"3dtiles": {
pbr: false
}
});
setTimeout(() => reearth.camera.flyTo(id), 100);
```
=> chore(web): disable PBR when material has texture

web/src/beta/lib/core/mantle/evaluator/simple/expression/node.ts
I added `rootProperties` built-in variables to access to some variables which has invalid character like `:`, `(` etc...
So we might be able to remove [replaceReservedWord](https://github.com/reearth/reearth/blob/main/web/src/beta/lib/core/mantle/evaluator/simple/expression/variableReplacer.ts#L109) in the future.
```js
const id = reearth.layers.add({
data: {
url: "https://assets.cms.plateau.reearth.io/assets/a2/33dad2-cb07-4cfa-90fa-724ac45c9aea/40202_omuta-shi_city_2023_citygml_1_op_bldg_3dtiles_lod1/tileset.json"
},
"3dtiles": {
color: {
expression: "${rootProperties['bldg:measuredHeight']} >= 20 ? color('red') : color('blue')"
}
}
});
setTimeout(() => {
reearth.camera.flyTo(id);
}, 100);
```
=> chore(web): support rootProperties built-in variables in evaluator

web/src/beta/lib/core/mantle/evaluator/simple/expression/functions/binaryFunctions.ts, web/src/beta/lib/core/mantle/evaluator/simple/index.test.ts
This PR adds support for `startsWith` to NLS style expression evaluator and corresponding test has been added.
=> chore(web): add startsWith func in style evaluator

web/src/beta/lib/core/Map/Layers/hooks.ts
`override`for layer and `updateStyle` could be called independently but in one frame, `overriddenLayers` state is not able to be updated, but `overriddenLayersRef.current = overriddenLayers;` is been called in each call, therefore the later update refs value from old `overriddenLayers` state and the first override could be override back.
This PR removes `overriddenLayersRef.current = overriddenLayers;`. Instead it set `overriddenLayersRef.current` to latest value at everywhere `setOverridenLayers` been used. When using overridden value use overriddenLayersRef.current to make sure it's getting the latest one.
=> chore(web): set overridden layers ref immediately

web/src/beta/lib/core/engines/Cesium/Feature/Resource/index.tsx
The timeline update params are incorrect.
=> chore(web): correct timeline update params

web/src/beta/lib/core/engines/Cesium/Feature/Resource/index.tsx, web/src/beta/lib/core/engines/Cesium/Feature/Resource/utils.ts
I fixed to be able to show infobox in VIEW3.0 in resource appearance with geojson.
You can use this dataset to test in VIEW3. It should show the feature inspector, but it doesn't show anything before.
`地震動予測（揺れやすさ）区域モデル（港区）`
=> chore(web): fix resource appearance to be able to get the information of the feature

web/src/beta/lib/core/mantle/evaluator/simple/expression/variableReplacer.ts, web/src/beta/lib/core/mantle/evaluator/simple/index.test.ts
This PR adds colon (`:`) as a reserved word in variableReplacer to bypass error produced by jsep while creating an AST and re:replace while accessing the properties for reals.
```{
"3dtiles": {
"color": {
"expression": {
"conditions": [
[
"${brid:class}==='桁橋'",
"color('#F9FD4C')"
]
]
}
},
"colorBlendMode": "highlight",
"pbr": false,
"shadows": "disabled"
}
}
```
Dataset: https://assets.cms.plateau.reearth.io/assets/b2/372698-305c-4963-b9b2-b3acc6bf745a/14100_yokohama-shi_city_2023_citygml_1_op_brid_3dtiles_lod2/tileset.json
=> chore(web): add colon as reserved word in style evaluator

web/src/beta/lib/core/Map/types/index.ts, web/src/beta/lib/core/engines/Cesium/core/Imagery.tsx, web/src/beta/lib/core/engines/Cesium/core/presets.ts
To prevent unnecessary request for tile server, I need to specify the maximumLevel and the minimumLevel to UrlTemplateImageryProvider.
=> chore(web): fix the zoomlevel for url

server/pkg/builtin/manifest.yml
This PR separately implements support for Infobox beta blocks extension in the `manifest.yml`
=> chore(server): seperate beta infobox blocks

server/pkg/builtin/manifest.yml, server/pkg/builtin/manifest_ja.yml
This PR adds support for googleAnalytics in `cesium-beta` manifest.yml
=> chore(server): add googleanalytics in cesium-beta manifest field

web/src/beta/lib/core/engines/Cesium/Feature/HeatMap/HeatmapMesh.tsx, web/src/beta/lib/core/engines/Cesium/pickMany.ts
This PR fixes an issue faced with pickMany when a groundPrimitive(like heatMap) is present in the scene.
=> fix(web): selection without groundPrimitives

web/src/beta/components/DragAndDropList/Item.tsx, web/src/beta/lib/core/shared/components/SelectableArea/ActionPanel/hooks.ts, web/src/beta/lib/core/shared/components/SelectableArea/ActionPanel/index.tsx, web/src/beta/lib/core/shared/components/SelectableArea/index.tsx
- Fix freeze on story blocks or infobox blocks if dnd drops outside of an item (needed to deselect and reselect again to do more dnd)
- Now non-selected items can dnd
- Moved preview to not include all of SelectArea. This cleans up the preview a bit so you don't see the select border, etc. The implementation adds a customPreview ref, so I think in the future we can customize the preview however we want.
=> chore(web): fix beta editor dnd

.github/workflows/_upload_cesium_token_txt.yml, .github/workflows/cron_ion_token.yml, .github/workflows/update_esium_ion_token_nightly.yml
Added cesium token cron for monthly updates
* Upload cesium ion token to gcs by cron
I have not been able to check the test because the inability to reference secrets in the forked branch.
This issue is related to the following PR. 
Additionally, the functionality has been tested in the Internal PR associated with the following PR.
ref https://github.com/reearth/reearth/pull/949
=> ci: add cesium token cron

web/src/beta/features/Visualizer/Crust/Infobox/Block/builtin/PropertyList/Content.tsx
`DisplayTypeField` could be undefined, missing `?` when using `displayTypeField.value`.
=> chore(web): fix beta infobox content error

web/src/beta/features/Editor/Visualizer/hooks.ts, web/src/beta/features/Editor/Visualizer/index.tsx, web/src/beta/features/Visualizer/index.tsx
This PR sets useExperimentalSandbox as true by default for beta.
=> chore(web): enable sandboxed iframe by default

.github/workflows/deploy_server_nightly.yml, .github/workflows/deploy_web_nightly.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, server/README.md, web/.storybook/theme.ts, web/README.md, web/package.json, web/src/beta/features/ProjectSettings/innerPages/PluginSettings/PluginInstall/PublicRepo/hooks.test.tsx, web/src/classic/components/molecules/Settings/Project/Plugin/PluginSection/PluginInstall/PublicRepo/hooks.test.tsx
This PR renames `reearth/reearth` repo to `reearth/reearth-visualizer` in this repo.
=> chore: rename reearth/reearth repo name to reearth/reearth-visualizer

.github/workflows/release.yml, .github/workflows/stage.yml
Reverts reearth/reearth-visualizer#1003
Because updating the protection branch was enough 👉 https://github.com/reearth/reearth-visualizer/actions/runs/9359266662
=> chore: revert addition of `--force` to push to protected branches

.github/workflows/release.yml, .github/workflows/stage.yml
Because it was just for testing and PoC-ing.
Remove the `--force` option.
=> chore: remove no need force for git push

web/src/beta/features/PublishedVisualizer/hooks.ts, web/src/beta/features/PublishedVisualizer/index.tsx
visualizerRef is required for plugins, it was missing in previous refactor around split core.
=> chore(web): missing visualizerRef on published page

web/src/beta/features/Visualizer/StoryPanel/Page/index.tsx, web/src/beta/features/Visualizer/StoryPanel/PanelContent/index.tsx, web/src/beta/features/Visualizer/StoryPanel/index.tsx, web/src/beta/features/Visualizer/index.tsx
It was missing when refactor the global jotai state.
Test the camera block on story page
=> chore(web): missing prop currentCamera for story built-in blocks

server/internal/usecase/interfaces/published.go, server/pkg/storytelling/story.go, server/pkg/storytelling/story_bulider.go, server/pkg/storytelling/story_bulider_test.go
This PR adds `coreSupport` as one of the Project and Story's Published Meta Data field.
=> feat(server): add coresupport as story and project metadata field

.github/workflows/deploy_server_nightly.yml
Because the GCR (Google Container Registry) will be decommissioned.
* [Transition from Container Registry, Google Cloud](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr) 
> Container Registry is deprecated and scheduled for shutdown. After May 15, 2024, Artifact Registry will host images for the gcr.io domain in Google Cloud projects without previous Container Registry usage
Changed the Docker registry to GAR.
=> ci: migrate GCR to GAR

web/src/beta/features/Editor/Map/index.tsx, web/src/beta/features/Editor/Publish/index.tsx, web/src/beta/features/Editor/Widgets/index.tsx, web/src/beta/features/PluginPlayground/Console/index.tsx, web/src/beta/features/PluginPlayground/PluginInspector/index.tsx, web/src/beta/features/PluginPlayground/Plugins/index.tsx, web/src/beta/features/PluginPlayground/Viewer/hooks.ts, web/src/beta/features/PluginPlayground/Viewer/index.tsx, web/src/beta/features/PluginPlayground/hooks.tsx, web/src/beta/features/PluginPlayground/index.tsx, web/src/beta/lib/reearth-ui/components/Tabs/index.stories.tsx, web/src/beta/lib/reearth-ui/components/Tabs/index.tsx, web/src/beta/lib/reearth-ui/components/index.ts, web/src/beta/pages/PluginPlaygroundPage/index.tsx, web/src/beta/ui/layout/Area/index.stories.tsx, web/src/beta/ui/layout/Area/index.tsx, web/src/services/routing/index.tsx
This PR adds the basic structure of plugin playground to help further development.
Added new router as `/plugin-playground`.
Also refactors some on Tab and Area component.
- Tab
- The switch tab logic should be handled internally and support controlled by props as well.
- Area
- Updates some on vertical collapse.
=> feat(web): basic structure of plugin playground

README.md
fixed the link in README.md
The link in Getting Started was incorrect.(go to 404 page)
=> docs: fix getting started link URL in README

web/vite.config.ts
We have no way to check which commit is being released in production environment so far. Also we can't know if we are using same version between front-end and back-end.
So I've exposed git commit hash on `window.REEARTH_COMMIT_HASH`. The same functionality is going to be added in back-end as well.
- Exposed git commit hash on `window.REEARTH_COMMIT_HASH`.
- Didn't for back-end
- Run `window.REEARTH_COMMIT_HASH` on browser console.
=> fix(web): expose git commit hash on window

web/src/main.tsx, web/src/services/config/index.ts, web/vite.config.ts
I added a functionality to embed git commit hash from vite define API in [this commit](https://github.com/reearth/reearth-visualizer/pull/1047), but the variable is removed in production build, so I fixed to assign the variable into `window` in runtime.
=> fix(web): embed git commit hash from vite in correct way

web/package.json, web/yarn.lock
Migration of Jotai to v2
I updated Jotai from v1.12.1 to v2.9.0
I checked through the docs (https://jotai.org/docs/guides/migrating-to-v2-api ) to check for any disparities in our code.
I tested Beta locally, both on my branch and on the main branch and nothing seemed to break on my end.
=> chore(web): Migrate Jotai to v2

web/src/services/api/layerStyleApi/index.ts, web/src/services/api/layersApi/index.ts, web/src/services/i18n/translations/en.yml, web/src/services/i18n/translations/ja.yml
PR amends a small typo to notifications when added and removing a layer style. I am wondering if we should use the word `remove` or `delete` as from the UI we display the word `delete` to the user.
=> chore(web): fix typo in layer style notifications

web/src/services/gql/provider/pagination.ts
Current implement is only doing connect results, finding `existing?.pageInfo.endCursor` in `merged` (which is a shadow copy of existing) doesn't make much secse.
When response from duplicated request coming, it will result in connect all which leads to duplicate item exists.
I changed it to find `incoming?.pageInfo.startCursor` in exist, and replace from the found item so that we can avoid duplicate item shows up.
=> fix(web): pagination with duplicate data fetch

web/package.json, web/yarn.lock
There's [breaking changes](https://github.com/justjake/quickjs-emscripten/blob/main/CHANGELOG.md#v0250) start from v0.25, higher version is not working well on current Visualizer on local. Downgrade this for now.
=> chore(web): downgrade quickjs-emscripten to v0.24.0

server/internal/adapter/gql/resolver_mutation_project.go
Cannot download with .reearth extension in CloudStrage
Revert the zip file extension
This is a speculative fix and cannot be confirmed until it is released.
https://www.notion.so/eukarya/BUG-Export-project-404-on-test-env-11316e0fb16580a3b042df5d12a679bc
=> fix(server): extension cahnge

.github/workflows/deploy_web_nightly.yml
It's required for the `gcloud` command's `--region` flag.
=> ci(web): add missing `GCP_REGION` environment variables

.github/workflows/build_server.yml, server/.goreleaser.yml
* [Announcing GoReleaser v2](https://goreleaser.com/blog/goreleaser-v2/)
=> ci: upgrade Goreleaser to use v2 configuration

web/.dockerignore, web/Dockerfile
Recently we introduced tailwind for web, the config of tailwind and postcss might be necessary for the build process.
Build docker image on my local and check the built files.
=> chore: add bind mounts tailwind and postcss config on docker build for web

web/src/beta/features/PluginPlayground/Plugins/presets/camera/cameraPosition.ts, web/src/beta/features/PluginPlayground/Plugins/presets/camera/cameraRotation.ts, web/src/beta/features/PluginPlayground/Plugins/presets/camera/zoomInOut.ts, web/src/beta/features/PluginPlayground/Plugins/presets/common.ts, web/src/beta/features/PluginPlayground/Plugins/presets/data/clientStorageThemeSelector.ts, web/src/beta/features/PluginPlayground/Plugins/presets/data/extensionProperty.ts, web/src/beta/features/PluginPlayground/Plugins/presets/data/messengerBetweenExtensions.ts, web/src/beta/features/PluginPlayground/Plugins/presets/data/uiExtensionMessenger.ts, web/src/beta/features/PluginPlayground/Plugins/presets/layerStyles/filterFeaturebyStyle.ts, web/src/beta/features/PluginPlayground/Plugins/presets/layerStyles/overrideStyle.ts, web/src/beta/features/PluginPlayground/Plugins/presets/layers/overrideLayerData.ts, web/src/beta/features/PluginPlayground/Plugins/presets/layers/showSelectedFeaturesInformation.ts, web/src/beta/features/PluginPlayground/Plugins/presets/timeline/playbackControl.ts, web/src/beta/features/PluginPlayground/Plugins/presets/viewer/enableShadowStyle.ts, web/src/beta/features/PluginPlayground/Plugins/presets/viewer/enableTerrain.ts, web/src/beta/features/PluginPlayground/Plugins/presets/viewer/mouseEvent.ts, web/src/beta/features/PluginPlayground/Plugins/presets/viewer/takeScreenshot.ts
=> fix(web): refactor styling to common styles

web/src/beta/features/PluginPlayground/Plugins/presets/camera/cameraRotation.ts, web/src/beta/features/PluginPlayground/Plugins/presets/camera/zoomInOut.ts, web/src/beta/features/PluginPlayground/Plugins/presets/common.ts, web/src/beta/features/PluginPlayground/Plugins/presets/data/extensionProperty.ts, web/src/beta/features/PluginPlayground/Plugins/presets/data/messengerBetweenExtensions.ts, web/src/beta/features/PluginPlayground/Plugins/presets/layerStyles/filterFeaturebyStyle.ts, web/src/beta/features/PluginPlayground/Plugins/presets/layerStyles/overrideStyle.ts, web/src/beta/features/PluginPlayground/Plugins/presets/layers/overrideLayerData.ts, web/src/beta/features/PluginPlayground/Plugins/presets/layers/showSelectedFeaturesInformation.ts, web/src/beta/features/PluginPlayground/Plugins/presets/viewer/mouseEvent.ts, web/src/beta/features/PluginPlayground/Plugins/presets/viewer/takeScreenshot.ts
Removed the default margin no the paragraph tag so that margin or spacing can be set through styles
Refactored plugins that used the paragraph tag and were affected by this margin
Added short descriptions to plugins that required them
=> fix(web): remove margin from paragraph tag and refactor plugin styles

server/internal/usecase/interactor/project.go, server/pkg/file/zip.go
We will limit the file size to 500MB when exporting and importing projects.
This is a preparation step for extending the timeout in Cloud Run.
=> chore(server): add file size check [VIZ-1425]

.github/workflows/license_checker.yml
Web project's package.json specifies the yarn version to v.4.6.0 while ci uses the global v1.22.22, this PR sets the yarn version for it.
=> chore(web): enable Corepack and set Yarn version in license checker workflow

server/Dockerfile
This pull request updates the `server/Dockerfile` to use a newer version of the Go programming language for the build process.
* [`server/Dockerfile`](diffhunk://#diff-7dcfbc368ef61cdb87ff87938d3901a82097fe398633f995dc4ab1cbee761a40L1-R1): Updated the base image from `golang:1.23.5-alpine` to `golang:1.24-alpine` to ensure compatibility with the latest Go features and improvements.
=> ci(server): changed golang version on dockerfile

server/e2e/gql_publish_test.go, server/e2e/proto_project_alias_test.go, server/e2e/proto_project_metadata_test.go, server/e2e/proto_project_test.go, server/e2e/proto_project_update_test.go, server/e2e/proto_project_user_test.go, server/internal/adapter/internalapi/schemas/internalapi/v1/schema.pb.go, server/internal/adapter/internalapi/schemas/internalapi/v1/schema_grpc.pb.go, server/internal/adapter/internalapi/server.go, server/internal/infrastructure/memory/project.go, server/internal/infrastructure/mongo/project.go, server/internal/usecase/interactor/project.go, server/internal/usecase/interactor/scene.go, server/internal/usecase/interactor/storytelling.go, server/internal/usecase/interfaces/project.go, server/internal/usecase/repo/project.go, server/pkg/alias/check.go, server/pkg/scene/scene.go, server/schemas/internalapi/docs/schema.md, server/schemas/internalapi/v1/schema.proto
```diff
// Find a project by alias.
// Request headers: user-id: <User ID>
rpc GetProjectByAlias(GetProjectByAliasRequest) returns (GetProjectByAliasResponse) {}
// Find a project by alias.
message GetProjectByAliasRequest {
// Scene alias
string alias = 1;
}
// Response messages
message GetProjectByAliasResponse {
// Project
Project project = 1;
}
```
```diff
// Determines if an alias is valid.
// Request headers: user-id: <User ID>
rpc ValidateProjectAlias(ValidateProjectAliasRequest) returns (ValidateProjectAliasResponse) {}
// Determines if an alias is valid.
message ValidateProjectAliasRequest {
// Project ID
optional string project_id = 1;
// Scene alias
string alias = 2;
}
// Response messages
message ValidateProjectAliasResponse {
// Project ID
optional string project_id = 1;
// …
```
=> feat(server): update project api alias [VIZ-1849]

web/src/app/features/Visualizer/Crust/Plugins/utils/events.ts, web/src/app/features/Visualizer/Crust/Plugins/utils/fingerprint.test.ts, web/src/app/features/Visualizer/Crust/Plugins/utils/fingerprint.ts
When using addEventListener and removeEventListener with functions created in QuickJS, the removal fails because the same logical function creates different JavaScript wrapper objects each time it's accessed from the host side.
Example of the problem:
```
// In QuickJS code
const myHandler = function() { console.log('clicked'); };
addEventListener('click', myHandler);        // Works - adds listener
removeEventListener('click', myHandler);     // Fails - myHandler is a different object!
```
This happens because:
1. QuickJS functions are marshaled/unmarshaled across the boundary
2. Each access creates a new JavaScript wrapper object
3. myHandler !== myHandler when accessed multiple times
4. removeEventListener can't find the handler to remove
Root Cause
The quickjs-emscripten-sync library …
=> fix(web): event off

server/internal/app/file_uploader.go
=> fix(server): bug fix for project import [VIZ-1945]

server/e2e/proto_project_alias_test.go, server/e2e/proto_project_sort_pagination_test.go, server/e2e/proto_project_test.go, server/e2e/proto_project_user_test.go, server/internal/adapter/gql/loader_project.go, server/internal/adapter/internalapi/internalapimodel/project.go, server/internal/adapter/internalapi/schemas/internalapi/v1/schema.pb.go, server/internal/adapter/internalapi/schemas/internalapi/v1/schema_grpc.pb.go, server/internal/adapter/internalapi/server.go, server/internal/infrastructure/memory/project.go, server/internal/infrastructure/mongo/project.go, server/internal/usecase/interactor/project.go, server/internal/usecase/interfaces/project.go, server/internal/usecase/repo/project.go, server/pkg/project/sort_type.go, server/schemas/internalapi/docs/schema.md, server/schemas/internalapi/v1/schema.proto
This API is identical to the GraphQL API.
```diff
+rpc PublishProject(PublishProjectRequest) returns (PublishProjectResponse) {}
+message PublishProjectRequest {
+  // Project ID (required)
+  string project_id = 1;
+  // Scene publication alias
+  optional string alias = 2;
+  // Scene publication status
+  PublishmentStatus publishment_status = 3;
+}
```
* When the workspace ID is not specified, it retrieves all projects from workspaces that the user either owns (owner) or belongs to (member).
Note: If the user is only a workspace member, projects marked as deleted will not be retrieved.
* Added options for sorting, keyword search, and pagination.
A dedicated sorting logic has been newly implemented instead of using reearthx.
Unlike the GraphQL GetProject, this implementation fixes a …
=> feat(server): update internal project api [VIZ-1962,VIZ-1961]

server/e2e/gql_project_test.go, server/e2e/proto_project_test.go, server/gql/project.graphql, server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/internal/adapter/gql/resolver_mutation_project.go, server/internal/adapter/internalapi/schemas/internalapi/v1/schema.pb.go, server/internal/adapter/internalapi/server.go, server/internal/usecase/interactor/project.go, server/internal/usecase/interfaces/project.go, server/schemas/internalapi/docs/schema.md, server/schemas/internalapi/v1/schema.proto
* GraphQL
```diff
input CreateProjectInput {
teamId: ID!
visualizer: Visualizer!
name: String
description: String
coreSupport: Boolean
visibility: String
projectAlias: String
+  # metadata
+  readme: String
+  license: String
+  topics: String
}
```
* Internal API
```diff
message CreateProjectRequest {
....
// Project alias
optional string project_alias = 7;
+  // Project readme
+  optional string readme = 8;
+  // Project license
+  optional string license = 9;
+  // Project topics
+  optional string topics = 10;
}
```
=> feat(server): add metadata for create project [VIZ-2026]

server/internal/infrastructure/mongo/migration/250724121006_set_visibility_public.go, server/internal/infrastructure/mongo/migration/250724121006_set_visibility_public_test.go, server/internal/infrastructure/mongo/migration/migrations.go
=> feat(server): set visibility public

server/e2e/gql_project_test.go, server/internal/usecase/interactor/project.go
During project import, a temporary project is first created using **CreateProject**,
and then it is updated via **ImportProjectData**.
At this time, an error occurs in the **CheckProjectAliasUnique** check
because the **ProjectAlias** becomes the same.
However, during **ImportProjectData**, the **ProjectAlias** is not carried over,
so **input.ProjectAlias** will always be nil.
We use this behavior to avoid the **CheckProjectAliasUnique** check.
=> fix(server): fixed the validation error during project import [VIZ-2071]

web/src/app/features/Visualizer/Crust/Plugins/utils/events.ts
After using fingerprint as the key, we resolved the issue that the callback cannot be removed correctly issue, but at the same time, it leads to another issue: once user bind the same function but the previous one is already out of lifecycle, it still returns the old one, it usually happens on plugin dev case.
Therefore this PR combined the solution, keep using callback itself as the key, but also check fingerprint when needed.
In detail, 
- when binding event, we use callback as key, and append fingerprint, in this case the new binding could always bind the correct one.
- when unbinding event, we check callback as key and also check fingerprint, so that the unbind could work as well.
=> refactor(web): enhance event callback management with fingerprint support

go.work.sum, server/e2e/gql_workspace_test.go, server/go.mod, server/go.sum, server/gql/workspace.graphql, server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/convert_workspace.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/internal/adapter/gql/resolver_mutation_workspace.go
```diff
input CreateWorkspaceInput {
name: String!
+    alias: String
}
input UpdateWorkspaceInput {
workspaceId: ID!
name: String!
+    alias: String
}
```
```
CheckWorkspaceAliasUnique(context.Context, workspace.ID, string) error
```
```
newAlias := fmt.Sprintf("w-%s", newId.String())
if alias != nil {
err := i.repos.Workspace.CheckWorkspaceAliasUnique(ctx, newId, *alias)
if err != nil {
return nil, err
}
newAlias = *alias
}
```
=> feat(server): add workspace alias [VIZ-2081]

server/e2e/common.go, server/e2e/gql_workspace_policy_test.go, server/gql/workspace.graphql, server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/internal/adapter/gql/resolver_query.go, server/internal/adapter/gql/resolver_workspace_policy_test.go, server/internal/usecase/gateway/policy_checker.go, server/internal/usecase/interactor/common.go, server/internal/usecase/interactor/policy.go, server/internal/usecase/interfaces/policy.go, server/pkg/policy/policy.go
1. GraphQL Schema Implementation
- Added workspacePolicyCheck(input: 
PolicyCheckInput!): PolicyCheckPayload
query to workspace.graphql
- Created PolicyCheckInput type with
workspaceId: ID! field
- Created PolicyCheckPayload type
returning workspaceId: ID! and
enableToCreatePrivateProject: Boolean!
2. Resolver Implementation
- Implemented WorkspacePolicyCheck
resolver method in resolver_query.go
- Added proper ID conversion from
GraphQL to domain types
- Connected resolver to policy usecase
with error handling
3. Backend Integration & Bug Fixes
- Fixed NewPolicy constructor in
policy.go to accept PolicyChecker
parameter
- Updated NewContainer in common.go to
pass g.PolicyChecker to policy
interactor
- Fixed e2e test setup by adding
policy.NewPermissiveChecker() to gateway
container
- …
=> feat(server): policy check query

server/e2e/gql_project_test.go, server/e2e/proto_project_user_test.go, server/internal/adapter/gql/gqlmodel/convert_project.go, server/internal/adapter/gql/resolver_mutation_project.go, server/internal/adapter/internalapi/server.go, server/internal/app/file_uploader.go, server/internal/usecase/interactor/project.go, server/internal/usecase/interfaces/project.go
* visibility
If the specified visibility is not allowed by the policy check, an error will be returned.
If the specified visibility is not allowed by the policy check, an error will be returned.
If the imported data has visibility set to private and it is not allowed, the system will attempt to create the project with public visibility.
If the visibility is public and not allowed, the system will attempt to create the project with private visibility instead.
=> feat(server): adjust visibility handling [VIZ-2110]

server/pkg/builtin/manifest.yml, server/pkg/builtin/manifest_ja.yml, web/src/services/i18n/translations/ja.yml
- Revises the Japanese translations to use "公開範囲" instead of "可視性" for project visibility-related terms. 
- Improves clarity and consistency in the UI by aligning terminology with intended meaning.
- Updates "MD Text" English and Japanese translation
=> fix(web): update japanese translations for project visibility terminology [VIZ-2153]

web/src/app/features/ProjectSettings/innerPages/PublicSettings/PublicSettingsDetail.tsx, web/src/app/features/ProjectSettings/innerPages/PublicSettings/index.tsx
`type` was missing on settingsItem, leading to the extension cannot be loaded.
=> fix(web): type missing on project public settings

server/.env.example, server/internal/app/config/file.go, server/internal/app/internal/middleware/assets_cors_middleware.go, server/internal/app/internal/middleware/assets_cors_middleware_test.go, server/internal/app/repo.go, server/internal/infrastructure/gcs/file.go, server/internal/usecase/interactor/published.go
- allow origin empty case because html img tag can't read image.
- we can fix front end to read img with origin by adding [attr](https://developer.mozilla.org/ja/docs/Web/HTML/Reference/Elements/img#crossorigin)  
- use `visualizer.WarnWithCallerLogging` to clear error cause.
- fix `file/gcs.go` to works fine to read file on fake-gcs
=> fix(server): story publishing isn't working

web/src/app/features/PluginPlayground/Code/hook.ts
Data attribution is needed for plugin playground as well.
=> feat(web): add data attribution widget to plugin playground

server/internal/app/app.go, server/internal/app/file_import_common.go, server/internal/app/file_signature_uploader.go, server/internal/app/file_split_uploader.go, server/internal/usecase/interactor/common.go, server/internal/usecase/interactor/project.go
```go
func GenFileName(workspaceID accountdomain.WorkspaceID, projectID id.ProjectID, userID accountdomain.UserID) string {
return fmt.Sprintf("%s-%s-%s.zip", workspaceID.String(), projectID.String(), userID.String())
}
```
```go
return func(c echo.Context) error {
req := c.Request()
ctx := req.Context()
...
if req.Method == "POST" && req.URL.Path == "/api/import-project" {
_, _, _, userID, err := SplitFilename(n.CloudEventData.Name)
...
u, err := cfg.AccountRepos.User.FindByID(ctx, *userID)
...
op, err := generateOperator(ctx, cfg, u)
...
ctx = adapter.AttachOperator(ctx, op)
```
=> feat(server): Allow access from storage trigger [VIZ-2232]

web/src/services/auth/useAuth.ts
iss stands for Issuer, and it’s a standard OpenID Connect (OIDC) claim that identifies which identity provider (tenant/domain) issued a token or performed an action.
When Auth0 sends users back to app after certain out-of-band flows (like password reset, email verification, or magic link login), it sometimes includes ?iss=https://YOUR_DOMAIN.auth0.com/ just as informational context.
It’s not part of the normal OAuth2 redirect (which would include ?code and ?state).
- The SDK detects code and state, calls handleRedirectCallback(), exchanges them for tokens, and logs the user in.
- The iss parameter is not used at any step in this process.
=> fix(web): clean up iss param
